import { reviews, crm, payments, accounting, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'event-tickets',
    name: 'Event Tickets and RSVP',
    label: 'Events',
    emoji: '🎟️',
    biz: 'Sunset Sessions Festival',
    who: 'attendee',
    journeyTitle: 'Attendee Journey – WhatsApp Events',
    lead: 'Attendees ask about the event, pick tickets, pay and receive a QR-code ticket without leaving WhatsApp. The bot also sends gate and parking info, handles ticket transfers and collects feedback after the event.',
    grad: '#075E54,#34B7F1',
    icon: '<path d="M15 40h90v14a8 8 0 0 0 0 16v14H15V70a8 8 0 0 0 0-16z"/><path d="M78 40v50" stroke-dasharray="5 5"/>',
    card: 'Answer event questions, sell tickets, send QR codes, handle transfers and reminders, and collect feedback.',
    active: 'Naledi Khumalo',
    contacts: [['Thabo Mokoena', '12 min ago', 'Can I bring my camera into the venue?'], ['Emma Clarke', '1 hour ago', 'Thanks, the QR code works!'], ['Pieter Botha', 'Yesterday', 'Is there parking for VIP?'], ['Aisha Patel', 'Sep 29, 2026', 'Please transfer my ticket to Zanele']],
    summary: [
      'Naledi asked about Sunset Sessions Festival. The bot gave the welcome menu.',
      'Event info shared: 14/11/2026, Boschendal Wine Estate, gates 12:00. Naledi wants tickets.',
      'Ticket type chosen: 2 x VIP at R1 450.00 each. Total R2 900.00.',
      'Order summary confirmed. Payment link sent. Reference SSF-2026-0412.',
      'Payment received. Two QR-code tickets issued and sent in chat.',
      'Reminder sent 13/11/2026 with parking and gate info. Naledi confirmed.',
      'Ticket transfer: 1 VIP ticket moved to Zanele Dlamini (new QR issued, old one cancelled).',
      'Post-event survey: Naledi rated 5/5 and shared feedback. Offered early-bird tickets for next year.',
    ],
  },

  chat: `  const steps = [
    ['Open the chat', [chip('Today'), O('Hi, tell me about Sunset Sessions'), I('Welcome to <b>Sunset Sessions Festival</b> 🎟️<br>What would you like to do?'), btns(['Event info', 'Buy tickets', 'My tickets'])]],
    ['Event info', [O('Event info'), I('<b>Sunset Sessions 2026</b>' + [['Date', '14/11/2026'], ['Gates open', '12:00'], ['Venue', 'Boschendal Wine Estate, Franschhoek'], ['Music until', '22:00']].map(([a, b]) => row(a, b)).join('')), btns(['Buy tickets', 'Ticket types'])]],
    ['Choose tickets', [O('Ticket types'), I('Here’s what is on offer:<br>🎫 <b>General</b> – R650.00 (lawn, food market)<br>⭐ <b>VIP</b> – R1 450.00 (deck, private bar, fast entry)'), btns(['General · R650', 'VIP · R1 450']), O('VIP · R1 450'), I('How many VIP tickets?'), btns(['1', '2', '3', '4']), O('2')]],
    ['Order and payment', [I('<b>Your order</b>' + [['2 x VIP', 'R2 900.00'], ['Booking fee', 'R0.00'], ['Total', 'R2 900.00', true]].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['Pay now', 'Change order']), O('Pay now'), I('Tap to pay securely by card or instant EFT:<br>🔗 pay.sunsetsessions.co.za/SSF-2026-0412'), btns(['Pay R2 900.00']), chip('Payment received')]],
    ['Your tickets', [I('✅ <b>You’re going!</b><br>Ref: SSF-2026-0412<br>Here are your 2 VIP tickets. Show the QR code at the gate.'), I('🎟️ <b>VIP ticket 1 of 2</b><br>[ QR code ]<br>Naledi Khumalo', '19:08'), I('🎟️ <b>VIP ticket 2 of 2</b><br>[ QR code ]<br>Naledi Khumalo', '19:08'), btns(['Add to calendar', 'Transfer a ticket'])]],
    ['Reminder', [chip('Fri 13/11/2026'), I('⏰ <b>Tomorrow is Sunset Sessions!</b><br>🚗 VIP parking: Gate B, opens 11:00<br>🚪 VIP entrance: Gate 2, fast lane<br>🎒 No glass bottles, small bags only', '09:00'), btns(['Directions', 'See you there']), O('See you there', '09:05')]],
    ['Transfer a ticket', [O('My friend Zanele can’t get a lift with me, can she have one ticket?', '09:20'), I('Of course! I’ll move 1 VIP ticket to her. What is her WhatsApp number?', '09:20'), O('082 555 0147', '09:21'), I('Transfer <b>1 VIP ticket</b> to Zanele Dlamini (082 555 0147)?<br>Your old ticket will stop working.', '09:21'), btns(['Confirm transfer', 'Cancel']), O('Confirm transfer', '09:22'), I('✅ Done! Zanele has her own QR code. Your other ticket still works.', '09:22')]],
    ['After the event', [chip('Sun 15/11/2026'), I('Thank you for joining <b>Sunset Sessions</b> 🌅 How was it? (1–5)', '10:00'), O('5 – Amazing day', '10:15'), I('So glad! Anything we should improve for next year?', '10:15'), btns(['Food queues', 'Parking', 'Nothing, perfect']), O('Nothing, perfect', '10:16'), I('Thank you! Early-bird tickets for 2027 open soon. Want us to message you first?', '10:16'), btns(['Yes, please', 'Not now'])]],
  ];`,

  journey: {
    lanes: ['Attendee (WhatsApp)', 'WhatsApp bot', 'Ticketing systems', 'Event team'],
    stages: [['Ask', 0, 2], ['Buy', 3, 8], ['Remind', 9, 12], ['Event', 13, 13], ['After', 14, 15]],
    nodes: [
      ['a1', 0, 0, 'start', 'Asks about\nSunset Sessions'],
      ['b1', 1, 1, 'step', 'Welcome and\nevent info'],
      ['a2', 2, 0, 'step', 'Picks General\nor VIP, quantity'],
      ['s1', 3, 2, 'system', 'Check ticket stock\non the platform'],
      ['d1', 4, 1, 'decision', 'Tickets\navailable?'],
      ['b2', 5, 1, 'step', 'Order summary and\npayment link'],
      ['a3', 6, 0, 'step', 'Pays on the\nsecure link'],
      ['s2', 7, 2, 'system', 'Payment confirmed,\nticket issued'],
      ['b3', 8, 1, 'step', 'Sends the\nQR-code tickets'],
      ['e1', 8, 3, 'human', 'Team gets the\nattendee count'],
      ['b4', 9, 1, 'step', 'Reminder with\nparking and gate'],
      ['a4', 10, 0, 'step', 'Asks to transfer\na ticket'],
      ['b5', 11, 1, 'step', 'Confirms transfer\nwith the attendee'],
      ['s3', 11, 2, 'system', 'Cancel old QR and\nissue a new one'],
      ['s4', 12, 2, 'system', 'Scanner checks\nthe QR at the gate'],
      ['v1', 13, 3, 'offline', 'Attendee enjoys\nthe event'],
      ['b6', 14, 1, 'step', 'Sends a short\nsurvey'],
      ['a5', 15, 0, 'end', 'Rates the event'],
    ],
    edges: [['a1', 'b1'], ['b1', 'a2'], ['a2', 's1'], ['s1', 'd1'], ['d1', 'b2', 'Yes'], ['d1', 'a2', 'No: suggest other type', 'back'], ['b2', 'a3'], ['a3', 's2'], ['s2', 'b3'], ['s2', 'e1'], ['b3', 'b4'], ['b4', 'a4'], ['a4', 'b5'], ['b5', 's3'], ['s3', 's4'], ['s4', 'v1'], ['v1', 'b6'], ['b6', 'a5']],
  },

  requirements: {
    intro: 'Sunset Sessions Festival sells tickets, delivers QR codes and handles reminders and transfers on WhatsApp. Most of the work sits in the ticketing platform you choose, so check its integration options first.',
    functions: [
      { fn: 'Ticket sales and stock', why: 'The bot shows ticket types and prices and knows when something sells out.',
        easy: ['Link to your ticket platform’s event page', 'The bot sends the buy link (for example from Quicket, Howler or Webtickets). Works with any platform, no integration needed.'],
        ideal: [['Howler', 'Publishes a Tickets API with an OpenAPI description (seen on the APIs.io network). Confirm what is open to organisers and whether you can create orders. ⚠'], ['Quicket', 'Large South African platform, now part of Ticketmaster. We could not find public API or webhook documentation. Ask Quicket directly. ⚠'], ['Webtickets or Computicket Box Office', 'No public API information found. Ask for organiser integration options. ⚠']],
        note: 'Ticket rules, fees and refunds are set by the platform. Do not promise a refund policy the platform does not support.' },
      { fn: 'QR-code tickets in chat', why: 'Deliver each ticket as a QR code the gate scanner accepts.',
        easy: ['Ticket link or PDF from the platform, sent in WhatsApp', 'The platform issues the ticket. The bot forwards the link or file.'],
        ideal: [['Your own QR generator tied to the platform’s ticket ID', 'Only if the platform lets you read ticket codes by API. Otherwise the scanner will not recognise them. ⚠']] },
      payments('Attendees pay for tickets with a secure payment link in the chat.'),
      { fn: 'Check-in at the gate', why: 'Scan QR codes at entry and stop duplicates.',
        easy: ['The ticket platform’s own scanner app', 'Most platforms offer access control (Quicket and Howler both list it). Staff scan the QR from the chat.'],
        ideal: [['Platform scanner with live check-in data', 'Lets the bot say “you have already entered” or count arrivals. Needs an API or export. ⚠']] },
      { fn: 'Ticket transfers', why: 'Let an attendee pass a ticket to a friend and cancel the old QR code.',
        easy: ['Team handles transfers from the platform’s dashboard', 'The bot collects the request, name and number. Staff move the ticket.'],
        ideal: [['Platform transfer feature or API', 'Check whether your platform has an official transfer option that voids the old code. ⚠']] },
      { fn: 'Reminders and event updates', why: 'Send gate, parking and weather updates before the event.',
        easy: ['Approved WhatsApp templates sent by S10U', 'S10U lists scheduled broadcasts with automatic opt-out. Opt-in is required.'],
        ideal: [['Reminders triggered from the ticket list', 'Needs the attendee list exported or read by API. ⚠']] },
      crm('Remember attendees, ticket types and who to message about next year.'),
      { fn: 'Survey and feedback', why: 'Ask for a rating after the event and collect comments.',
        easy: ['In-chat rating saved to a Google Sheet', 'Simple and free.'],
        ideal: [['Survey tool or the CRM', 'Trends over several events.']] },
      accounting,
      handover,
    ],
  },
};
