import { reviews, crm, payments, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'gym-classes',
    name: 'Gym Classes',
    label: 'Gym',
    emoji: '🏋️',
    biz: 'Iron Peak Fitness',
    who: 'member',
    journeyTitle: 'Member Journey – WhatsApp Class Booking',
    lead: 'Members see the timetable, book a class and cancel or join a waiting list in WhatsApp. Full classes fill up again by themselves, so fewer spots go empty and the front desk answers fewer calls.',
    grad: '#075E54,#25D366',
    icon: '<path d="M10 60h100"/><path d="M28 38v44M44 28v64M76 28v64M92 38v44"/>',
    card: 'Members book gym classes on WhatsApp: timetable, spot check, waiting list, reminders, cancellations and ratings.',
    active: 'Naledi Khumalo',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Spin class on Friday is booked. Thanks!'],
      ['Emma Clarke', '1 hour ago', 'Can I freeze my membership for December?'],
      ['Pieter Botha', 'Yesterday', 'Got the waiting list spot, see you at 06:00'],
      ['Aisha Patel', 'Sep 29, 2026', 'Loved the yoga class, 5 out of 5'],
    ],
    summary: [
      'Naledi Khumalo opened the chat. Intent: see what classes are on.',
      'Interested in Spin on Thursday 15/10/2026 at 17:30 with coach Sipho.',
      'Membership checked: Premium, active. Spin has 2 spots left. Spot reserved.',
      'Booked: Spin, 15/10/2026 17:30, ref IP-2026-0214. Calendar invite sent.',
      'Saturday Yoga is full. Naledi joined the waiting list at position 2.',
      'Reminder sent the day before. Naledi confirmed she is coming.',
      'Cancelled Spin inside the free window. Spot released and offered to the waiting list.',
      'A Yoga spot opened up. Naledi accepted it automatically and is booked for 17/10/2026.',
      'Rated the Yoga class 5 out of 5. Offered next week’s class.',
    ],
  },

  chat: `  const steps = [
    ['Open the chat', [chip('Today'), O('Hi, what classes are on this week?'), I('Welcome to <b>Iron Peak Fitness</b> 🏋️<br>I can book your spot in a class. What would you like to do?'), btns(['See the timetable', 'My bookings', 'Membership'])]],
    ['Choose a class', [O('See the timetable'), I('Which type of class are you after?'), btns(['Spin', 'Yoga', 'HIIT', 'Boxing']), O('Spin'), I('Spin classes next week:<br>• Mon 12/10 · 06:00<br>• Wed 14/10 · 18:00<br>• Thu 15/10 · 17:30<br>• Sat 17/10 · 09:00'), btns(['Thu 15/10 · 17:30', 'Other days']), O('Thu 15/10 · 17:30')]],
    ['Membership and spot check', [I('One moment, I’m checking your membership and the class… ⏳'), I('✅ Your <b>Premium</b> membership is active until 30/11/2026.<br>Spin with <b>Sipho</b> has <b>2 spots left</b>. Shall I book you in?'), btns(['Book my spot', 'Choose another time']), O('Book my spot')]],
    ['Confirm', [I('<b>Booking summary</b>' + [['Class', 'Spin'], ['Coach', 'Sipho'], ['Date', '15/10/2026'], ['Time', '17:30'], ['Studio', 'Iron Peak, Sandton']].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['Confirm', 'Change']), O('Confirm'), I('✅ <b>You’re booked!</b><br>Ref: IP-2026-0214<br>Free cancellation up to 3 hours before the class.'), btns(['Add to calendar', 'Manage booking'])]],
    ['Full class and waiting list', [O('Is there space in Saturday’s yoga at 08:00?'), I('Saturday’s <b>Yoga Flow</b> at 08:00 is <b>fully booked</b> (20/20) 🙈<br>I can add you to the waiting list. If a spot opens up, I’ll message you straight away.'), btns(['Join the waiting list', 'No thanks']), O('Join the waiting list'), I('You’re <b>number 2</b> on the waiting list for Yoga Flow, Sat 17/10/2026 at 08:00. Ref: IP-2026-0215')]],
    ['Reminder', [chip('Wed 14/10/2026'), I('⏰ Reminder: <b>Spin</b> with Sipho is tomorrow at 17:30. Bring a towel and water bottle!', '17:30'), btns(['See you there', 'Cancel my spot']), O('Actually something came up. I need to cancel.', '17:42')]],
    ['Cancel inside the free window', [I('No problem. You’re inside the free cancellation window (more than 3 hours before), so no charge and your credits stay as they are.<br>Cancel <b>Spin, Thu 15/10 · 17:30</b>?', '17:42'), btns(['Yes, cancel', 'Keep my spot']), O('Yes, cancel', '17:43'), I('✅ Cancelled. Ref: IP-2026-0214.<br>I’ve released your spot to the next member on the waiting list automatically.', '17:43'), chip('Staff are notified: class list updated')]],
    ['Waiting list spot offered', [chip('Wed 14/10/2026'), I('Good news Naledi! 🎉 A spot just opened in <b>Yoga Flow</b>, Sat 17/10 at 08:00. It’s yours for the next 30 minutes.', '17:45'), btns(['Take the spot', 'No thanks']), O('Take the spot', '17:46'), I('✅ <b>You’re in!</b> Yoga Flow, Sat 17/10/2026 at 08:00 with Lindiwe.<br>Ref: IP-2026-0215', '17:46')]],
    ['After the class', [chip('Sat 17/10/2026'), I('Thanks for joining <b>Yoga Flow</b> today at <b>Iron Peak Fitness</b> 💚 How was the class? (1–5)', '09:20'), O('5 – Loved it', '09:35'), I('Awesome, thank you! Shall I book your next yoga class for Sat 24/10 at 08:00?', '09:35'), btns(['Book Sat 24/10', 'Not now']), O('Book Sat 24/10', '09:36'), I('Checking your spot… ✅ Booked! Ref: IP-2026-0231. See you then 🧘', '09:36')]],
  ];`,

  journey: {
    lanes: ['Member (WhatsApp)', 'WhatsApp bot', 'Gym systems', 'Gym staff'],
    stages: [['Browse', 0, 4], ['Check and book', 5, 8], ['Remind', 9, 9], ['Cancel', 10, 13], ['Class', 14, 16]],
    nodes: [
      ['m1', 0, 0, 'start', 'Member asks what\nclasses are on'],
      ['b1', 1, 1, 'step', 'Welcome and\ntimetable menu'],
      ['s1', 2, 2, 'system', 'Read the class\ntimetable'],
      ['b2', 3, 1, 'step', 'Shows classes\nand times'],
      ['m2', 4, 0, 'step', 'Picks Spin on\nThursday 17:30'],
      ['d1', 5, 2, 'decision', 'Membership\nactive?'],
      ['h1', 6, 3, 'human', 'Staff help with\nrenewal'],
      ['d2', 7, 2, 'decision', 'Spot free?'],
      ['b3', 8, 1, 'step', 'Confirms booking\nor offers waiting list'],
      ['s2', 9, 2, 'system', 'Save the booking\nand send reminder'],
      ['b4', 10, 1, 'step', 'Reminder the day\nbefore'],
      ['m3', 11, 0, 'step', 'Cancels inside\nthe free window'],
      ['s3', 12, 2, 'system', 'Free the spot, offer\nit to waiting list'],
      ['r1', 13, 3, 'human', 'Staff see the\nupdated class list'],
      ['v1', 14, 3, 'offline', 'Member trains\nin the class'],
      ['b5', 15, 1, 'step', 'Asks for a rating,\noffers next class'],
      ['m4', 16, 0, 'end', 'Rates the class'],
    ],
    edges: [
      ['m1', 'b1'], ['b1', 's1'], ['s1', 'b2'], ['b2', 'm2'], ['m2', 'd1'],
      ['d1', 'd2', 'Yes'], ['d1', 'h1', 'No'],
      ['d2', 'b3', 'Free or full'],
      ['b3', 's2'], ['s2', 'b4'], ['b4', 'm3'], ['m3', 's3'], ['s3', 'r1'],
      ['r1', 'v1'], ['v1', 'b5'], ['b5', 'm4'],
    ],
  },

  requirements: {
    intro: 'Iron Peak Fitness books classes, runs the waiting list and handles cancellations on WhatsApp. These are the pieces behind each step of the demo.',
    functions: [
      { fn: 'Class timetable, spots and bookings', why: 'The bot reads the timetable, checks how many spots are left and saves the booking.',
        easy: ['Google Calendar or a Google Sheet', 'Free. One row per class with a capacity number. The bot writes the booking and staff keep the sheet up to date.'],
        ideal: [['Octiv Fitness', 'South African gym and studio software with Netcash debit orders. Check whether its API is open to third parties. ⚠'], ['Itensity', 'South African gym software with local debit order providers. Check API access. ⚠'], ['Mindbody, Glofox or Wodify', 'International tools that are also used here. Mindbody lists an open API. Check cost, ZAR billing and API access for your plan. ⚠']],
        note: 'Most gym software only allows new bookings through its own app or a partner integration. Ask the vendor before promising live bookings from WhatsApp. ⚠' },
      { fn: 'Membership status', why: 'Check the member is active, paid up and has classes or credits left.',
        easy: ['Member list in a Google Sheet', 'The bot looks up the member by cell number. Staff update it each month.'],
        ideal: [['The membership module of your gym software', 'Live status, freezes and credits. Needs the integration above. ⚠']],
        note: 'Membership and payment status is personal information. Show only “active” or “not active” in chat. ⚠' },
      { fn: 'Waiting list', why: 'When a class is full, hold a queue and offer a freed spot to the next person.',
        easy: ['A waiting list tab in the Google Sheet, run by an automation tool (Make, n8n or Zapier)', 'A new free spot triggers a template message to the next name, with a 30 minute time limit.'],
        ideal: [['The waiting list built into your gym software', 'Mindbody, Glofox and others list waitlists. Confirm whether the bot can trigger them through an API. ⚠']] },
      { fn: 'Membership payments and debit orders', why: 'Monthly fees are collected automatically and late payers are flagged.',
        easy: ['Netcash debit orders via your gym software', 'Netcash advertises gym and fitness debit order solutions and an integration with Octiv. ⚠'],
        ideal: [['Itensity with Netcash, PayGate, ThreePeaks or Bitventure', 'Several local collection providers are listed by Itensity. Confirm DebiCheck support. ⚠'], ['Paystack or Ozow', 'For once-off drop-in fees and top-ups. API and payment links.']] },
      payments('Drop-in fees, class packs and late-cancellation fees can be paid from WhatsApp.'),
      { fn: 'Reminders and calendar', why: 'Remind members the day before and add the class to their calendar.',
        easy: ['Approved WhatsApp templates sent by S10U plus a Google Calendar invite', 'Free-form messages are only allowed 24 hours after the member’s last message, so reminders use templates.'],
        ideal: [['Reminders triggered by the gym software', 'Fires when a booking is created or changed. Needs the integration above. ⚠']] },
      { fn: 'Cancellation rules', why: 'Apply the free cancellation window and release the spot.',
        easy: ['Rule written into the bot (for example free up to 3 hours before)', 'Staff change the hours when the policy changes.'],
        ideal: [['Rules held in the gym software', 'One source of truth for late cancellations and no-shows. ⚠']] },
      crm('Remember each member’s favourite classes, coach and last visit.'),
      reviews,
      handover,
    ],
  },
};
