import { crm, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'loyalty-rewards',
    name: 'Loyalty and Rewards',
    label: 'Loyalty',
    emoji: '🎁',
    biz: 'Bean There Coffee Roasters',
    who: 'member',
    journeyTitle: 'Member Journey – WhatsApp Loyalty',
    lead: 'Customers join the rewards programme by scanning a QR code at the till. The bot tracks points, shows rewards, issues voucher codes that staff scan, and sends birthday, referral and expiry messages.',
    grad: '#075E54,#25D366',
    icon: '<rect x="22" y="50" width="76" height="52" rx="6"/><path d="M16 36h88v14H16zM60 36v66M60 36c-8-18-30-18-28-6 2 8 16 6 28 6zM60 36c8-18 30-18 28-6-2 8-16 6-28 6z"/>',
    card: 'Customers join by QR code, earn points, check their balance, redeem vouchers and get birthday and expiry messages.',
    active: 'Naledi Khumalo',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Voucher scanned, thanks!'],
      ['Emma Clarke', '1 hour ago', 'How many points do I have?'],
      ['Pieter Botha', 'Yesterday', 'I referred my brother 🎉'],
      ['Aisha Patel', 'Sep 29, 2026', 'Thanks for the birthday treat 👍'],
    ],
    summary: [
      'Scanned the QR code at the till and asked to join.',
      'Joined the rewards programme. Consent saved, birthday 14/11.',
      'Purchase of R78.00 added 78 points. Balance 78.',
      'Asked for her balance: 342 points.',
      'Chose the free flat white (300 points).',
      'Voucher BT-RW-4821 issued. Valid 24 hours.',
      'Voucher scanned in store. Balance 42 points.',
      'Birthday reward sent: free pastry on 14/11/2026.',
      'Friend referred: 100 bonus points each. Expiry reminder sent.',
    ],
  },

  chat: `  const steps = [
    ['Scan the QR code', [chip('Today'), O('Hi, I’d like to join the rewards'), I('Welcome to <b>Bean There Coffee Roasters</b> ☕<br>Earn a point for every R1 you spend and swap them for free coffee.'), btns(['Join rewards', 'How it works'])]],
    ['Join with consent', [O('Join rewards'), I('Great! May we save your name and number to run your rewards, and send you offers on WhatsApp?<br>You can reply <b>STOP</b> any time to opt out.'), btns(['Yes, I agree', 'No thanks']), O('Yes, I agree'), I('What is your first name and birthday? (for a treat on your day 🎂)'), O('Naledi, 14/11'), I('✅ Welcome, <b>Naledi</b>! Your member number is <b>BT-2026-0214</b>.')]],
    ['Earn points', [chip('Later, after your purchase'), I('Thanks for visiting our Gardens shop, Cape Town ☕<br>Purchase: <b>R78.00</b><br>You earned <b>78 points</b>.', '08:12'), btns(['Check my points']), O('Thanks!', '08:13')]],
    ['Check balance', [chip('Two weeks later'), O('How many points do I have?'), I('<b>Your rewards</b>' + [['Member', 'BT-2026-0214'], ['Points', '342'], ['Expire on', '30/04/2027', true]].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['See rewards', 'Done'])]],
    ['Choose a reward', [O('See rewards'), I('You can swap your points for:'), btns(['Flat white · 300 pts', 'Bag of beans 250g · 800 pts', 'Free pastry · 200 pts']), O('Flat white · 300 pts'), I('Redeem a free flat white for <b>300 points</b>?'), btns(['Yes, redeem', 'Not now'])]],
    ['Voucher code', [O('Yes, redeem'), I('🎟️ Your voucher code is <b>BT-RW-4821</b><br>Show this to the barista. Valid for 24 hours at any Bean There shop.'), btns(['Show QR code'])]],
    ['Used in store', [chip('At the till'), O('Show QR code', '08:05'), I('[QR code · BT-RW-4821]', '08:05'), chip('Barista scans the code'), I('✅ Voucher used at <b>Gardens, Cape Town</b>. Enjoy your flat white!<br>Points left: <b>42</b>.', '08:06')]],
    ['Birthday reward', [chip('Sat 14/11/2026'), I('🎂 Happy birthday, <b>Naledi</b>! Here is a free pastry on us. Code <b>BT-BD-1114</b>, valid until 21/11/2026.', '08:00'), btns(['Thank you!', 'Show QR code']), O('Thank you!', '08:20'), I('Enjoy your day 🎉', '08:20')]],
    ['Refer and expiry', [O('Can I share this with a friend?'), I('Yes! Send your friend this link. When they join, you both get <b>100 bonus points</b>.<br>wa.me/27215550142?text=Join%20BT-2026-0214'), btns(['Share link']), O('Share link'), chip('Fri 16/04/2027'), I('⏰ Heads up: <b>180 points</b> expire on 30/04/2027. Swap them for a free pastry before then!', '09:00'), btns(['See rewards', 'Not now']), I('Reply <b>STOP</b> any time to stop these messages.', '09:00')]],
  ];`,

  journey: {
    lanes: ['Member (WhatsApp)', 'WhatsApp bot', 'Loyalty systems', 'Shop staff'],
    stages: [['Join', 0, 3], ['Earn', 4, 6], ['Balance', 7, 9], ['Redeem', 10, 14], ['Keep engaged', 15, 18]],
    nodes: [
      ['m1', 0, 0, 'start', 'Scans the QR code\nat the till'],
      ['b1', 1, 1, 'step', 'Welcome, consent and\nreply STOP note'],
      ['m2', 2, 0, 'step', 'Agrees, gives name\nand birthday'],
      ['s1', 3, 2, 'system', 'Create member and\nsave consent in CRM'],
      ['h0', 4, 3, 'human', 'Cashier rings up\nthe sale'],
      ['s2', 5, 2, 'system', 'POS sale adds points\nto the ledger'],
      ['b3', 6, 1, 'step', 'Sends points\nearned'],
      ['m3', 7, 0, 'step', 'Asks: how many\npoints do I have?'],
      ['s3', 8, 2, 'system', 'Read balance from\nthe points ledger'],
      ['b4', 9, 1, 'step', 'Shows balance and\nrewards'],
      ['m4', 10, 0, 'step', 'Picks a reward\nand redeems'],
      ['d1', 11, 2, 'decision', 'Enough points?'],
      ['s4', 12, 2, 'system', 'Take points and\ncreate voucher code'],
      ['b5', 13, 1, 'step', 'Sends voucher\nand QR code'],
      ['h1', 14, 3, 'human', 'Staff scan the\nvoucher at the till'],
      ['b6', 15, 1, 'step', 'Sends birthday\nreward'],
      ['m5', 16, 0, 'step', 'Shares referral link\nwith a friend'],
      ['b7', 17, 1, 'step', 'Reminds that points\nare about to expire'],
      ['m6', 18, 0, 'end', 'Swaps points\nbefore they expire'],
    ],
    edges: [['m1', 'b1'], ['b1', 'm2'], ['m2', 's1'], ['s1', 'h0'], ['h0', 's2'], ['s2', 'b3'], ['b3', 'm3'], ['m3', 's3'], ['s3', 'b4'], ['b4', 'm4'], ['m4', 'd1'], ['d1', 's4', 'Yes'], ['d1', 'b4', 'No: show what they can get', 'back'], ['s4', 'b5'], ['b5', 'h1'], ['h1', 'b6'], ['b6', 'm5'], ['m5', 'b7'], ['b7', 'm6']],
  },

  requirements: {
    intro: 'Bean There Coffee Roasters runs a WhatsApp rewards programme across its shops. These are the pieces behind each step of the demo. Research checked 7 October 2026; items marked ⚠ need a check with the vendor.',
    functions: [
      { fn: 'Points ledger', why: 'Keeps each member’s points, rewards and expiry dates.',
        easy: ['A Google Sheet', 'Free. One row per member, one per transaction. Fine for one or two shops but easy to break and not safe for concurrent updates.'],
        ideal: [['Yoco Loyalty', 'Yoco says every card payment on its terminals earns points automatically, with no app. Only works if the shops use Yoco terminals. Whether the points can be read from outside Yoco is not confirmed. ⚠'], ['A loyalty tool with an API', 'Many tools exist, but check each one for rand pricing, an open API and local support. ⚠']],
        note: 'Pick one place for the points balance and treat it as the single source of truth.' },
      { fn: 'Sales data from the till (POS)', why: 'Each sale needs to reach the ledger so points are earned automatically.',
        easy: ['Staff type the member number into the POS or a Google Form', 'No integration. Slower, and staff can forget.'],
        ideal: [['Yoco', 'Has a developer hub with payment and webhook APIs. Webhooks announce payments, but whether they carry item or customer detail should be confirmed. ⚠'], ['Lightspeed Restaurant (O-Series)', 'Lists API documentation, webhooks and a loyalty and payments API for partners. Access terms need checking. ⚠'], ['Other South African POS systems', 'Check each for an API before promising a link. ⚠']] },
      { fn: 'QR code and joining', why: 'The till QR code opens WhatsApp with the join message ready.',
        easy: ['A wa.me link turned into a QR code', 'Free. Print it at the till and on cups or receipts.'],
        ideal: [['Different QR codes per shop', 'Lets you see which shop signs up the most members.']] },
      { fn: 'Consent and opt-out', why: 'Members agree to messages and can stop any time.',
        easy: ['Consent saved in the CRM with date and wording', 'S10U lists broadcasts with automatic opt-out. Keep your own record too.'],
        ideal: [['Consent field synced to the CRM and POS', 'Stops messages if someone replies STOP.']],
        note: 'Under POPIA, tell members why you collect their name, number and birthday. Birthday is used only for the reward. Keep a record of consent. Get legal sign-off. ⚠' },
      crm('Stores each member, birthday, consent and referral link.'),
      { fn: 'Vouchers and redemption', why: 'The member gets a code and staff scan it at the till.',
        easy: ['Unique codes in the sheet, staff tick them off', 'Free. Needs discipline to avoid double use.'],
        ideal: [['Voucher or discount codes in your POS', 'Staff scan one code and the till applies it. Confirm your POS supports one-time codes. ⚠'], ['S10U in-chat vouchers', 'S10U lists payments with vouchers, but not loyalty vouchers. Ask what it can do. ⚠']] },
      { fn: 'Birthday and expiry messages', why: 'Sends rewards and reminders outside the 24-hour window.',
        easy: ['Approved WhatsApp templates sent by broadcast', 'S10U lists scheduled broadcasts and templates. Prepare the list daily from the sheet.'],
        ideal: [['CRM automation (HubSpot or Zoho)', 'Triggers the message from the birthday or expiry date field.']] },
      { fn: 'Referral tracking', why: 'Credits both members when a friend joins.',
        easy: ['A referral code in the join message', 'The bot reads the code and credits points by hand or via sheet.'],
        ideal: [['Automation tool (Make, n8n or Zapier)', 'Credits both ledgers automatically. Confirm the link with S10U. ⚠']] },
      handover,
    ],
  },
};
