import { reviews, payments, accounting, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'quote-request',
    name: 'Quote Request',
    label: 'Quotes',
    emoji: '📋',
    biz: 'Cape Plumbing & Drainage',
    who: 'customer',
    journeyTitle: 'Customer Journey – WhatsApp Quotes',
    lead: 'Customers describe the problem, send photos and get a rough call-out range straight away. The bot books the site visit, sends the formal quote as a PDF, takes the deposit and asks for a review after the job.',
    grad: '#075E54,#34B7F1',
    icon: '<path d="M30 15h45l20 20v70H30z"/><path d="M75 15v20h20M42 55h38M42 72h38M42 89h24"/>',
    card: 'Describe the problem, send photos, get a rough price, book a site visit, receive the quote and pay the deposit.',
    active: 'Naledi Khumalo',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Photo of the blocked drain'],
      ['Emma Clarke', '1 hour ago', 'Thanks, I accept the quote'],
      ['Pieter Botha', 'Yesterday', 'Can you quote for a new bathroom?'],
      ['Aisha Patel', 'Sep 29, 2026', '5 – the team was great'],
    ],
    summary: [
      'Naledi Khumalo opens a chat about a plumbing problem. Status: new enquiry.',
      'Problem: leaking geyser, 3 photos received, suburb Observatory, urgent.',
      'Rough call-out and assessment range given: R650 to R950. Waiting for a visit time.',
      'Site visit booked: Tuesday 10/11/2026, 09:00–11:00. Ref CPD-2026-0412.',
      'Technician Sipho visited and measured. Quote being prepared by the office.',
      'Formal quote Q-0412 for R6 850.00 sent as a PDF. Waiting for the customer.',
      'Quote accepted. Deposit of R2 055.00 paid. Job scheduled for 13/11/2026.',
      'Job completed. Review requested and 5 stars received.',
    ],
  },

  chat: `  const steps = [
    ['Describe the problem', [chip('Today'), O('Hi, my geyser is leaking in the ceiling. Can you quote?'), I('Welcome to <b>Cape Plumbing & Drainage</b> 🔧<br>Sorry to hear that. Let’s get you sorted. Can you send me a few photos of the geyser and the leak?'), btns(['Send photos', 'Call me instead'])]],
    ['Photos, suburb and urgency', [O('Send photos'), I('Please send up to 5 photos 📷'), O('📷 3 photos', '08:14'), I('Thanks, I can see the geyser and the water stain. Which suburb are you in?', '08:14'), O('Observatory, Cape Town', '08:15'), I('How urgent is it?', '08:15'), btns(['Burst or flooding now', 'Today or tomorrow', 'This week', 'Just planning']), O('Today or tomorrow', '08:15')]],
    ['Rough call-out range', [I('Thank you, Naledi. For a leaking geyser in Observatory, the site visit and assessment usually costs <b>R650 to R950</b>.<br>The final price depends on the geyser size and the work needed. You get a formal quote after the visit, and there is no obligation to accept it.', '08:16'), btns(['Book a site visit', 'Ask a question']), O('Book a site visit', '08:17')]],
    ['Book the site visit', [I('Which day suits you?', '08:17'), btns(['Tomorrow, Tue 10/11', 'Wed 11/11', 'Thu 12/11']), O('Tomorrow, Tue 10/11', '08:18'), I('Free arrival windows:', '08:18'), btns(['09:00 – 11:00', '13:00 – 15:00']), O('09:00 – 11:00', '08:18'), I('<b>Site visit booked</b>' + [['Name', 'Naledi Khumalo'], ['Address', 'Observatory, Cape Town'], ['Job', 'Leaking geyser'], ['Date', '10/11/2026'], ['Window', '09:00 – 11:00'], ['Call-out fee', 'R650 – R950', true]].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['Confirm', 'Change']), O('Confirm', '08:19'), I('✅ <b>Booked!</b><br>Ref: CPD-2026-0412<br>Sipho, our technician, will message you when he is on his way.', '08:19')]],
    ['After the visit', [chip('Tue 10/11/2026'), I('Hi Naledi, Sipho is 20 minutes away 🚗', '08:40'), O('Great, I’m home', '08:41'), chip('Later that day'), I('Thanks for having us today. Sipho has sent his measurements and notes. Our office is preparing your formal quote and will send it here, usually within 24 hours.', '13:05')]],
    ['The quote arrives', [chip('Wed 11/11/2026'), I('Your quote is ready 📄<br><b>Quote Q-0412</b><br>Replace 150 L geyser, new pressure valve and drip tray', '09:30'), I('📎 Quote-Q-0412.pdf · 2 pages', '09:30'), I('<b>Quote summary</b>' + [['Geyser and valve', 'R5 450.00'], ['Labour', 'R1 400.00'], ['Total incl. VAT', 'R6 850.00', true], ['Deposit (30%)', 'R2 055.00']].map(([a, b, bold]) => row(a, b, bold)).join('') + '<br>Valid until 25/11/2026.', '09:30'), btns(['Accept quote', 'Ask a question', 'Not now']), O('Accept quote', '10:02')]],
    ['Deposit and scheduling', [I('Thank you! To book the work, please pay the <b>R2 055.00</b> deposit. The balance is due when the job is done.', '10:02'), btns(['Pay deposit now']), O('Pay deposit now', '10:03'), I('🔒 Secure payment link: pay.example.co.za/cpd-0412', '10:03'), chip('Payment received'), I('✅ Deposit received, thank you!<br><b>Job scheduled:</b> Fri 13/11/2026, 08:00, Sipho and one assistant. Please clear access to the geyser. A tax invoice has been emailed to you.', '10:05')]],
    ['After the job', [chip('Fri 13/11/2026'), I('Your new geyser is in, and the job is signed off ✅ Thank you for choosing <b>Cape Plumbing & Drainage</b>. How was our service? (1–5)', '14:30'), O('5 – Sipho was brilliant, no mess at all', '15:10'), I('That is wonderful to hear! Would you share it as a Google review? It helps other homeowners find us.', '15:10'), btns(['Leave a Google review', 'Maybe later']), O('Leave a Google review', '15:11'), I('Thank you, Naledi! Your 12-month workmanship cover is on your invoice. Message us any time 💙', '15:11')]],
  ];`,

  journey: {
    lanes: ['Customer (WhatsApp)', 'WhatsApp bot', 'Business systems', 'Technician and office'],
    stages: [['Enquire', 0, 3], ['Site visit', 4, 9], ['Quote', 10, 13], ['Accept and pay', 14, 16], ['Job and review', 17, 19]],
    nodes: [
      ['p1', 0, 0, 'start', 'Describes the problem\n(leaking geyser)'],
      ['b1', 1, 1, 'step', 'Welcome, asks for\nphotos'],
      ['p2', 2, 0, 'step', 'Sends photos, suburb\nand urgency'],
      ['b2', 3, 1, 'step', 'Gives rough call-out\nfee range'],
      ['s1', 4, 2, 'system', 'Check the calendar\nfor visit slots'],
      ['b3', 5, 1, 'step', 'Offers visit times'],
      ['p3', 6, 0, 'step', 'Picks a time'],
      ['s2', 7, 2, 'decision', 'Slot still\nfree?'],
      ['b4', 8, 1, 'step', 'Confirms visit with\na reference'],
      ['t1', 9, 3, 'offline', 'Technician visits\nand measures up'],
      ['t2', 10, 3, 'human', 'Office prepares\nthe formal quote'],
      ['s3', 11, 2, 'system', 'Quote PDF created\nin quoting tool'],
      ['b5', 12, 1, 'step', 'Sends the quote\nas a PDF'],
      ['p4', 13, 0, 'step', 'Accepts the quote'],
      ['b6', 14, 1, 'step', 'Sends deposit\npayment link'],
      ['s4', 15, 2, 'system', 'Payment received,\ninvoice created'],
      ['b7', 16, 1, 'step', 'Confirms the job date'],
      ['v1', 17, 3, 'offline', 'Job done and\nsigned off'],
      ['b8', 18, 1, 'step', 'Asks for a rating\nand a review'],
      ['p5', 19, 0, 'end', 'Leaves a review'],
    ],
    edges: [['p1', 'b1'], ['b1', 'p2'], ['p2', 'b2'], ['b2', 's1'], ['s1', 'b3'], ['b3', 'p3'], ['p3', 's2'], ['s2', 'b4', 'Yes'], ['s2', 'b3', 'No: offer other times', 'back'], ['b4', 't1'], ['t1', 't2'], ['t2', 's3'], ['s3', 'b5'], ['b5', 'p4'], ['p4', 'b6'], ['b6', 's4'], ['s4', 'b7'], ['b7', 'v1'], ['v1', 'b8'], ['b8', 'p5']],
  },

  requirements: {
    intro: 'Cape Plumbing & Drainage turns a WhatsApp message with photos into a booked site visit, a formal quote, a paid deposit and a review. These are the pieces behind each step. Checked 7 October 2026.',
    functions: [
      { fn: 'Photos and job details', why: 'The customer sends photos and the bot saves them with the job so the office can see the problem.',
        easy: ['S10U shared inbox', 'S10U lists images in its shared inbox, so the team sees the photos. Saving them to a job card needs a link through an API or an automation tool (Make, n8n, Zapier), to be confirmed with S10U.'],
        ideal: [['Photos saved to Google Drive or the job tool', 'An automation copies each photo to a folder named after the job reference. ⚠'], ['Job-management app', 'Fergus, Tradify and ServiceM8 keep photos on the job. Check whether each has an open API you can use. ⚠']] },
      { fn: 'Site visit calendar', why: 'The bot checks the technician’s free windows and books the visit.',
        easy: ['Google Calendar per technician', 'Free, with an API. Staff see the day on their phones.'],
        ideal: [['Job-management scheduling (ServiceM8, Fergus or Tradify)', 'Dispatch and a technician app. They appear on the Xero South Africa app marketplace. Check local support and API access. ⚠'], ['Microsoft 365 / Outlook', 'If the office already uses it.']] },
      { fn: 'Call-out fee range', why: 'The bot gives a rough range by job type and area, before the visit.',
        easy: ['A price table in the bot’s knowledge base', 'You choose the ranges and the bot repeats them. Always say the final price is on the formal quote.'],
        ideal: [['Price list kept in the quoting tool', 'One source for call-out fees, parts and labour, so the bot and the quotes agree. ⚠']],
        note: 'Keep ranges clearly marked as estimates, not final prices.' },
      { fn: 'Formal quotes and PDFs', why: 'The office prepares the quote and the bot sends it as a PDF.',
        easy: ['Quotes in Xero or Zoho Books', 'Both can create quotes and turn an accepted quote into an invoice. Staff send the PDF in the chat. Confirm the quote features on your plan. ⚠'],
        ideal: [['Sage Business Cloud Accounting', 'South African-origin, with a REST API. Quote features depend on the plan. ⚠'], ['Quotient or a job-management app', 'Quotient is listed for sending quotes that become Xero invoices. Fergus, Tradify and ServiceM8 also quote and invoice. Check price in rand and local availability. ⚠']] },
      { fn: 'Quote acceptance', why: 'The customer taps “accept” and the quote is marked as won.',
        easy: ['Accept button in the chat, status set by the team', 'The bot records the reply and the office marks the quote accepted.'],
        ideal: [['Status change sent to the quoting tool', 'An automation (Make, n8n or Zapier) marks the quote accepted when the button is tapped. ⚠']] },
      payments('The customer pays a deposit by payment link before the job is scheduled.'),
      { fn: 'Job scheduling and team alerts', why: 'Once the deposit is paid, the job gets a date and the crew is told.',
        easy: ['Google Calendar entry plus a WhatsApp or email alert to the office', 'Simple and free. The office confirms the crew and date.'],
        ideal: [['Job-management app dispatch', 'Assigns the job and sends the crew the address and photos. ⚠']] },
      reviews, accounting, handover,
    ],
  },
};
