import { payments, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'school-fees',
    name: 'School and Fees',
    label: 'School',
    emoji: '🎓',
    biz: 'Bluegum Primary School',
    who: 'parent',
    journeyTitle: 'Parent Journey – WhatsApp School Updates',
    lead: 'Parents check fee balances, pay, get circulars and report absences on WhatsApp. The office stops answering the same calls all day.',
    grad: '#075E54,#34B7F1',
    icon: '<path d="M10 45L60 20l50 25-50 25z"/><path d="M30 57v22c0 8 60 8 60 0V57"/><path d="M110 45v30"/>',
    card: 'Parents verify, see the fee balance, pay by link, get circulars with RSVP and report absences.',
    active: 'Nomsa Dlamini',
    contacts: [
      ['Pieter Botha', '12 min ago', 'Thanks, I’ve paid the term fees'],
      ['Aisha Patel', '1 hour ago', 'Can I get a statement for Zayd?'],
      ['Sipho Ndlovu', 'Yesterday', 'Yes, we’ll be at sports day'],
      ['Emma Clarke', 'Sep 29, 2026', 'Lily is sick today, back Monday'],
    ],
    summary: [
      'Parent Nomsa Dlamini asked for a fee balance. Waiting to verify her identity.',
      'Parent verified with an SMS code and matched to her child Amahle (Grade 4). Nothing shown before this.',
      'Balance shown: R4 850.00 outstanding for Term 4. Parent chose to pay.',
      'Payment link sent for R4 850.00. Waiting for payment.',
      'Payment received. Receipt BPS-2026-0412 sent. Fee account updated.',
      'School circular sent: Sports Day, 24/10/2026. Parent has not replied yet.',
      'RSVP recorded: 2 adults attending sports day for Amahle.',
      'Absence reported for Amahle (Grade 4B), 07/10/2026, sick. Class teacher and office notified.',
    ],
  },

  chat: `  const steps = [
    ['Ask about fees', [chip('Today'), O('Hi, what is the fee balance for my child?', '07:42'), I('Welcome to <b>Bluegum Primary School</b> 🎓<br>I can help with fees, school news and absences. First I need to check it’s really you.', '07:42'), I('I’ve sent a 6-digit code by SMS to the cellphone number the school has on file ending <b>•••• 4471</b>.', '07:42'), btns(['I didn’t get a code', 'Talk to the school office'])]],
    ['Verify the parent', [O('482915', '07:43'), I('✅ Thank you, Nomsa. You’re verified.<br>For privacy, I only share details for children linked to your number.', '07:43'), I('Which child?', '07:43'), btns(['Amahle · Grade 4', 'Sipho · Grade 1']), O('Amahle · Grade 4', '07:43')]],
    ['Fee balance', [I('<b>Fee account · Amahle Dlamini</b>' + [['Term 4 fees', 'R7 850.00'], ['Paid so far', 'R3 000.00'], ['Balance due', 'R4 850.00', true], ['Due date', '31/10/2026']].map(([a, b, bold]) => row(a, b, bold)).join(''), '07:44'), btns(['Pay now', 'Send me a statement', 'Payment arrangement']), O('Pay now', '07:44')]],
    ['Payment link', [I('Here is your secure payment link for <b>R4 850.00</b>. You can pay by card or instant EFT.', '07:44'), btns(['Pay R4 850.00 securely']), chip('Parent pays on the payment page'), O('Done, I’ve paid', '07:47')]],
    ['Receipt', [I('✅ Payment received. Thank you, Nomsa!', '07:47'), I('<b>Receipt</b>' + [['Reference', 'BPS-2026-0412'], ['Amount paid', 'R4 850.00'], ['Date', '07/10/2026'], ['Balance due', 'R0.00', true]].map(([a, b, bold]) => row(a, b, bold)).join(''), '07:47'), btns(['Download receipt', 'Back to menu'])]],
    ['School circular', [chip('Two weeks later'), I('📣 <b>Bluegum Primary School</b><br><b>Sports Day</b><br>Saturday 24/10/2026 at 08:30 at the school field. Pupils wear house colours. Tuckshop and coffee on sale.<br>Will you be attending?', '16:05'), btns(['Yes, attending', 'No, can’t make it', 'More details'])]],
    ['RSVP', [O('Yes, attending', '16:20'), I('Great! How many adults will join Amahle?', '16:20'), btns(['1', '2', '3 or more']), O('2', '16:21'), I('✅ Thank you! We’ve noted <b>2 adults</b> for Amahle on 24/10/2026. We’ll send a reminder the day before.', '16:21')]],
    ['Report an absence', [chip('Monday'), O('Amahle is sick today', '06:58'), I('I’m sorry to hear that. Let me note it for the school. Will she be out for more than today?', '06:58'), btns(['Just today', 'A few days']), O('Just today', '06:59'), I('✅ <b>Absence recorded</b>' + [['Pupil', 'Amahle Dlamini · Grade 4B'], ['Date', '12/10/2026'], ['Reason', 'Sick'], ['Reference', 'BPS-ABS-0237']].map(([a, b]) => row(a, b)).join('') + '<br>Her class teacher, Mrs Naidoo, and the school office have been told. A note from a doctor is only needed after 3 days. Get well soon, Amahle! 💛', '06:59'), btns(['Report another absence', 'Back to menu'])]],
  ];`,

  journey: {
    lanes: ['Parent (WhatsApp)', 'WhatsApp bot', 'School systems', 'School office'],
    stages: [['Verify', 0, 5], ['Pay', 6, 11], ['Circular', 12, 14], ['Absence', 15, 19]],
    nodes: [
      ['p1', 0, 0, 'start', 'Parent asks for the\nfee balance'],
      ['b1', 1, 1, 'step', 'Welcomes and asks\nfor an SMS code'],
      ['p2', 2, 0, 'step', 'Types the code'],
      ['s1', 3, 2, 'system', 'Check the code and\nnumber on file'],
      ['d1', 4, 2, 'decision', 'Parent\nverified?'],
      ['b2', 5, 1, 'step', 'Shows the child’s\nfee balance'],
      ['p3', 6, 0, 'step', 'Taps Pay now'],
      ['s2', 7, 2, 'system', 'Create a payment\nlink for the amount'],
      ['b3', 8, 1, 'step', 'Sends the\npayment link'],
      ['p4', 9, 0, 'step', 'Pays by card\nor instant EFT'],
      ['s3', 10, 2, 'system', 'Payment confirmed,\nfee account updated'],
      ['b4', 11, 1, 'step', 'Sends the receipt'],
      ['o1', 12, 3, 'human', 'Office sends the\nsports day circular'],
      ['b5', 13, 1, 'step', 'Delivers circular\nwith RSVP buttons'],
      ['p5', 14, 0, 'step', 'Taps Yes and\nnumber attending'],
      ['p6', 15, 0, 'step', 'Reports “Amahle\nis sick today”'],
      ['b6', 16, 1, 'step', 'Logs the absence\nand confirms'],
      ['o2', 17, 3, 'human', 'Class teacher and\noffice see the absence'],
      ['b7', 18, 1, 'step', 'Tells parent the\nteacher has been told'],
      ['p7', 19, 0, 'end', 'Parent gets the\nconfirmation'],
    ],
    edges: [
      ['p1', 'b1'], ['b1', 'p2'], ['p2', 's1'], ['s1', 'd1'],
      ['d1', 'b2', 'Yes'], ['d1', 'b1', 'No: ask again', 'back'],
      ['b2', 'p3'], ['p3', 's2'], ['s2', 'b3'], ['b3', 'p4'], ['p4', 's3'], ['s3', 'b4'],
      ['b4', 'o1'], ['o1', 'b5'], ['b5', 'p5'], ['p5', 'p6'],
      ['p6', 'b6'], ['b6', 'o2'], ['o2', 'b7'], ['b7', 'p7'],
    ],
  },

  requirements: {
    intro: 'Bluegum Primary School answers fee questions, takes payments, sends circulars and logs absences on WhatsApp. Children’s and family financial data is sensitive, so the bot verifies the parent first.',
    functions: [
      { fn: 'Parent verification', why: 'Confirm it is the registered parent before showing any fee or child details.',
        easy: ['SMS or WhatsApp code to the cellphone number on the school’s record', 'The bot only answers for children linked to that number. Wrong code or unknown number goes to the office.'],
        ideal: [['Check against the school system’s guardian list', 'Match the number to the parent record automatically. Needs the school system link below. ⚠'], ['Extra check for sensitive requests', 'For example, ask for the child’s date of birth before sending a statement.']],
        note: 'Children’s data and family finances are protected by POPIA. Never share a balance or child name until the parent is verified, and log who asked. ⚠' },
      { fn: 'School administration and fee system', why: 'Where learners, parents and fee accounts live. The bot reads the balance from here.',
        easy: ['An exported fee list (CSV or Google Sheet) updated by the bursar', 'Cheap and fine for a demo or a small school. The balance is only as fresh as the last export.'],
        ideal: [['D6 (d6+ and D6 Communicator)', 'Widely used South African school platform covering admin, finance and parent communication. Whether it offers an open API to third parties is not stated publicly. Ask D6. ⚠'], ['SchoolSpeak, Edupac or a Pastel-based fee system', 'Common in South African schools. API access was not verified for any of them, so expect a vendor partnership or an export. ⚠']],
        note: 'Fee and child records are personal information under POPIA. Keep the data in the school system and read it live instead of copying it. ⚠' },
      payments('Parents pay the outstanding balance from WhatsApp.'),
      { fn: 'Debit orders and payment arrangements', why: 'Offer parents who cannot pay in full a monthly plan.',
        easy: ['Bot collects the request, the bursar agrees the plan', 'No system link. The bot never promises terms.'],
        ideal: [['Debit orders through the school’s bank or a collection provider', 'Many schools already use bank debit orders. Check with the school’s bank or the fee system for how new mandates are loaded. ⚠'], ['Paystack or Ozow recurring options', 'Recurring card or bank payments may be possible. Confirm availability for your account. ⚠']] },
      { fn: 'Receipts and fee account updates', why: 'After payment the parent gets a receipt and the account shows the balance as paid.',
        easy: ['Gateway sends a payment confirmation, the bursar allocates it', 'Safe, with a human step. The receipt in chat is a payment confirmation.'],
        ideal: [['Payment webhook that updates the school system automatically', 'Possible only if the fee system accepts incoming payments through an API or an import file. ⚠'], ['Xero or Sage Business Cloud Accounting', 'If the school keeps its books there. Both have APIs.']] },
      { fn: 'Circulars and RSVP', why: 'Send school news to parents and collect yes or no replies.',
        easy: ['WhatsApp broadcast template with reply buttons from S10U', 'S10U lists broadcasts with scheduling and automatic opt-out. Replies saved to a Google Sheet.'],
        ideal: [['Circular created in the school app, copied to WhatsApp', 'D6 Communicator and similar apps already send circulars. Confirm whether they can trigger WhatsApp messages. ⚠'], ['Make, n8n or Zapier', 'Link the RSVP replies to the school’s calendar or list. Confirm the S10U connection with S10U.']],
        note: 'Parents must opt in to WhatsApp messages from the school. Use approved templates outside the 24-hour window.' },
      { fn: 'School calendar', why: 'Sports day, holidays and events the bot can answer about and remind.',
        easy: ['Google Calendar kept by the school office', 'Free. The bot answers from the events you add.'],
        ideal: [['The calendar inside the school platform', 'Keeps one calendar for the app and WhatsApp. Access depends on the vendor. ⚠'], ['Microsoft 365 / Outlook', 'If the school uses it.']] },
      { fn: 'Absence reporting', why: 'Parent tells the school a child is absent. The class teacher and office see it at once.',
        easy: ['Bot writes to a shared sheet and emails or messages the class teacher', 'Simple and visible to the office.'],
        ideal: [['Write the absence to the school attendance register', 'Needs an API or import from the school system. Not verified for D6, SchoolSpeak or Edupac. ⚠']],
        note: 'The bot records the date and a short reason. Do not collect medical detail. Health reasons about a child are sensitive under POPIA. ⚠' },
      { fn: 'Language options', why: 'Parents may prefer isiZulu, Afrikaans or another language.',
        easy: ['Bot answers in the language the parent writes in', 'S10U states its chatbots work in 11 languages. Check quality for the languages your parents use.'],
        ideal: [['Approved templates in each home language', 'Gives control over wording of fees and circulars.']] },
      handover,
    ],
  },
};
