import { reviews, crm, payments, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'takeaway-order',
    name: 'Takeaway Order',
    label: 'Takeaway',
    emoji: '🍔',
    biz: 'Braai Bru Burgers',
    who: 'customer',
    journeyTitle: 'Customer Journey – WhatsApp Takeaway',
    lead: 'Customers order food on WhatsApp: they pick items, tweak them, choose delivery or collection and pay with a link. The kitchen gets the order and the customer gets live updates until the food arrives.',
    grad: '#075E54,#25D366',
    icon: '<path d="M24 62h72a36 36 0 0 0-72 0z"/><path d="M20 76h80M26 90h68a8 8 0 0 1-8 8H34a8 8 0 0 1-8-8z"/>',
    card: 'Customers order food on WhatsApp, pay by link and follow delivery updates until it arrives.',
    active: 'Sipho Dlamini',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Out for delivery, thanks!'],
      ['Emma Clarke', '1 hour ago', 'Can I collect at 18:30?'],
      ['Pieter Botha', 'Yesterday', 'Burger was great 🍔'],
      ['Aisha Patel', 'Sep 29, 2026', 'Payment received 👍'],
    ],
    summary: [
      'Customer wants to order food.',
      'Chose Burgers: Braai Bru Classic (R89.00).',
      'No onions, extra sauce. Added large chips and a Coke.',
      'Delivery to 14 Protea Road, Table View (location pin).',
      'Order total R174.00 including R25.00 delivery.',
      'Paid by payment link. R174.00 received.',
      'Order BB-2026-0412 confirmed. ETA 35 minutes.',
      'Out for delivery, then arrived at 19:41.',
      'Rated 5 – Loved it. Reorder offered.',
    ],
  },

  chat: `  const steps = [
    ['Open the chat', [chip('Today'), O('Hi, I’d like to order food'), I('Welcome to <b>Braai Bru Burgers</b> 🍔<br>Hungry? What would you like to do?'), btns(['Order now', 'See the menu', 'Opening hours'])]],
    ['Pick from the menu', [O('Order now'), I('Pick a category:'), btns(['Burgers', 'Kota and wraps', 'Sides', 'Drinks']), O('Burgers'), I('Our burgers 🔥'), btns(['Braai Bru Classic · R89', 'Double Boerie Stack · R119', 'Chicken Peri-Peri · R95']), O('Braai Bru Classic · R89')]],
    ['Make it yours', [I('Any changes to your <b>Braai Bru Classic</b>?'), btns(['No onions', 'Extra sauce', 'Both']), O('Both'), I('Noted: <b>no onions, extra sauce</b> ✅<br>Add large chips (R38) and a Coke 440ml (R22)?'), btns(['Add both', 'Chips only', 'No thanks']), O('Add both')]],
    ['Delivery or collection', [I('Delivery or collection?'), btns(['Delivery', 'Collect in store']), O('Delivery'), I('Please share your location pin or type your address 📍'), O('📍 Location shared'), I('Got it: <b>14 Protea Road, Table View</b>. We deliver there in about 35 minutes.')]],
    ['Order total', [I('<b>Your order</b>' + [['Braai Bru Classic', 'R89.00'], ['No onions, extra sauce', ''], ['Large chips', 'R38.00'], ['Coke 440ml', 'R22.00'], ['Delivery fee', 'R25.00'], ['Total', 'R174.00', true]].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['Pay now', 'Change order']), O('Pay now')]],
    ['Pay by link', [I('Pay securely with card or instant EFT:<br><span style="color:#027EB5">pay.braaibru.co.za/BB0412</span>'), btns(['Pay R174.00']), O('Done, paid'), I('✅ Payment of <b>R174.00</b> received. Thank you!')]],
    ['Order confirmed', [I('🎉 <b>Your order is in!</b><br>Order no: BB-2026-0412<br>Estimated time: <b>35 minutes</b><br>The kitchen is already firing up the grill.'), btns(['Track my order', 'Add a note'])]],
    ['Delivery updates', [chip('19:12'), I('👨‍🍳 Your order is being prepared.', '19:12'), chip('19:28'), I('🛵 <b>Out for delivery.</b> Your driver Lwazi is on his way.', '19:28'), O('Thanks! I’m home', '19:29'), chip('19:41'), I('📍 Your driver has <b>arrived</b>. Enjoy your meal!', '19:41')]],
    ['Rate your order', [chip('Later that evening'), I('Thanks for ordering from <b>Braai Bru Burgers</b> 💚 How was your meal? (1–5)', '20:30'), O('5 – Loved it', '20:32'), I('Shot! Want the same order next time?', '20:32'), btns(['Reorder this', 'Not now']), O('Not now', '20:33'), I('No problem. See you next time 🍔', '20:33')]],
  ];`,

  journey: {
    lanes: ['Customer (WhatsApp)', 'WhatsApp bot', 'Ordering systems', 'Kitchen and driver'],
    stages: [['Order', 0, 4], ['Details', 5, 7], ['Pay', 8, 10], ['Confirm', 11, 12], ['Cook and deliver', 13, 16]],
    nodes: [
      ['c1', 0, 0, 'start', 'Customer says hi'],
      ['b1', 1, 1, 'step', 'Welcome and menu\ncategories'],
      ['s1', 2, 2, 'system', 'Load today’s menu\nand sold-out items'],
      ['c2', 3, 0, 'step', 'Picks items, no\nonions, extra sauce'],
      ['b2', 4, 1, 'step', 'Delivery or\ncollection?'],
      ['c3', 5, 0, 'step', 'Chooses delivery,\nsends location pin'],
      ['d1', 6, 2, 'decision', 'Address inside\ndelivery area?'],
      ['b3', 7, 1, 'step', 'Shows total with\ndelivery fee'],
      ['s2', 8, 2, 'system', 'Create payment link\n(card or instant EFT)'],
      ['c4', 9, 0, 'step', 'Pays the link'],
      ['d2', 10, 2, 'decision', 'Payment\nreceived?'],
      ['b4', 11, 1, 'step', 'Confirms order\nnumber and ETA'],
      ['s3', 12, 2, 'system', 'Send to POS and\nkitchen printer'],
      ['k1', 13, 3, 'human', 'Kitchen cooks and\npacks the order'],
      ['k2', 14, 3, 'offline', 'Driver delivers\nto the door'],
      ['b5', 15, 1, 'step', 'Sends: out for\ndelivery, arrived'],
      ['c5', 16, 0, 'end', 'Gets the food\nand rates it'],
    ],
    edges: [['c1', 'b1'], ['b1', 's1'], ['s1', 'c2'], ['c2', 'b2'], ['b2', 'c3'], ['c3', 'd1'], ['d1', 'b3', 'Yes'], ['d1', 'b2', 'No: offer collection', 'back'], ['b3', 's2'], ['s2', 'c4'], ['c4', 'd2'], ['d2', 'b4', 'Yes'], ['d2', 'b3', 'No: resend link', 'back'], ['b4', 's3'], ['s3', 'k1'], ['k1', 'k2'], ['k2', 'b5'], ['b5', 'c5']],
  },

  requirements: {
    intro: 'Braai Bru Burgers takes orders, payments and delivery updates on WhatsApp. These are the pieces behind each step of the demo.',
    functions: [
      { fn: 'Menu and stock', why: 'The bot shows today’s menu and hides items that are sold out.',
        easy: ['Menu in the bot’s knowledge base or a Google Sheet', 'Free. Staff tick items off when they run out.'],
        ideal: [['Your POS or online ordering menu as the single source', 'Prices and sold-out items stay in sync, with no double typing. Needs an API from the POS vendor. ⚠']] },
      { fn: 'POS and kitchen printer', why: 'Paid orders land in the kitchen without anyone retyping them.',
        easy: ['Order sent to a kitchen email, WhatsApp group or Google Sheet', 'Simple, cheap, works on day one. Staff key it into the till.'],
        ideal: [['Yoco POS or a restaurant POS with an open API', 'Orders print on the kitchen printer. Confirm API access with the vendor. ⚠'], ['Online ordering middleware such as orderTalk (owned by Uber Eats)', 'Connects many South African POS systems. Check whether it accepts orders from your own channel. ⚠']] },
      payments('Customers pay the order total from the chat before the kitchen starts.'),
      { fn: 'Delivery area and fee', why: 'Work out if the address is in range and add the delivery fee.',
        easy: ['A fixed fee per suburb list kept in the bot', 'No code. Good for a small delivery area.'],
        ideal: [['Google Maps Platform (Geocoding and Distance Matrix)', 'Fee by distance from the shop. Billed in USD, usage-based. Check current pricing. ⚠']] },
      { fn: 'Delivery', why: 'Someone must get the food to the customer.',
        easy: ['Your own drivers, updated by the kitchen with a button or WhatsApp group', 'You keep the full order value. Staff post “out for delivery” and “arrived”.'],
        ideal: [['Delivery platforms: Mr D Food and Uber Eats', 'Large reach. Commission is reported at about 20% to 30%, so confirm your own rates. A WhatsApp order usually cannot use their drivers. ⚠'], ['A driver app or on-demand courier with an API', 'Live tracking and dispatch. Check which South African providers offer a public API. ⚠']],
        note: 'Delivery platforms are mostly sales channels, not a way to send your own WhatsApp orders to their drivers. Confirm before promising it. ⚠' },
      { fn: 'Order status updates', why: 'Tell the customer when the food is preparing, out for delivery and arrived.',
        easy: ['Staff tap a status in a shared sheet or inbox', 'The bot sends the update. Free-form messages work inside the 24-hour chat window.'],
        ideal: [['Status changes from the POS or driver app trigger the message', 'Hands-free. Needs the integrations above. Messages outside the 24-hour window need an approved template.']] },
      crm('Remember each customer’s address, favourite order and allergies for faster reorders.'),
      { fn: 'Reorders and specials', why: 'Offer “same again” and send weekly specials to opted-in customers.',
        easy: ['Last order stored in the CRM or a Google Sheet', 'Offer “Reorder this” after each order.'],
        ideal: [['Broadcast campaigns with approved templates', 'S10U lists scheduling and automatic opt-out. Opt-in is required.']] },
      reviews, handover,
    ],
  },
};
