import { reviews, crm, payments, accounting, handover } from '../requirements.mjs';

export default {
  meta: {
    slug: 'vehicle-service',
    name: 'Vehicle Service',
    label: 'Garage',
    emoji: '🔧',
    biz: 'Kloof Road Auto Care',
    who: 'customer',
    journeyTitle: 'Customer Journey – WhatsApp Vehicle Service',
    lead: 'Customers book a service, approve extra repairs with a photo and quote, follow progress and pay, all in WhatsApp. The workshop spends less time on the phone and gets repair approvals in writing.',
    grad: '#075E54,#128C7E',
    icon: '<circle cx="60" cy="60" r="16"/><path d="M60 14v18M60 88v18M14 60h18M88 60h18M27 27l13 13M80 80l13 13M93 27L80 40M40 80L27 93"/>',
    card: 'Customers book a service, approve extra repairs from a photo and quote, get status updates, pay by link and get reminders.',
    active: 'Sipho Dlamini',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Great, I’ll collect at 16:30'],
      ['Emma Clarke', '1 hour ago', 'Can I book a brake check?'],
      ['Pieter Botha', 'Yesterday', 'Thanks, the car drives like new'],
      ['Aisha Patel', 'Sep 29, 2026', 'Please send the quote again'],
    ],
    summary: [
      'Customer wants to book a vehicle service.',
      'Toyota Corolla 2019, registration CA 123-456, 62 000 km. Full service.',
      'Drop-off Mon 16/11/2026 at 07:30. Slot held.',
      'Booking confirmed. Ref KR-2026-0214. Reminder sent the day before.',
      'Technician found worn front brake pads. Photo and quote R1 380.00 sent.',
      'Customer approved the extra repair. Job card updated.',
      'Status updates sent: in the workshop, ready for collection. Final bill R2 940.00.',
      'Paid R2 940.00 by payment link. Rated the service 5 out of 5.',
      'Next service reminder sent after 6 months. Customer asked to book.',
    ],
  },

  chat: `  const steps = [
    ['Open the chat', [chip('Today'), O('Hi, I need to book my car in for a service'), I('Welcome to <b>Kloof Road Auto Care</b> 🔧<br>How can we help today?'), btns(['Book a service', 'Get a quote', 'Check my car’s status'])]],
    ['Vehicle details', [O('Book a service'), I('Which vehicle is it? Please send the make, model and year.'), O('Toyota Corolla 2019'), I('Thanks! And the registration number?'), O('CA 123-456'), I('Got it: <b>Toyota Corolla 2019, CA 123-456</b>. What service do you need?'), btns(['Basic service', 'Full service', 'Something else']), O('Full service')]],
    ['Drop-off slot', [I('Which day suits you for drop-off?'), btns(['📅 Pick a date']), O('16/11/2026'), I('Free drop-off times on <b>Mon 16/11/2026</b>:'), btns(['07:30', '08:30', '10:00']), O('07:30')]],
    ['Confirm booking', [I('<b>Booking summary</b>' + [['Vehicle', 'Corolla, CA 123-456'], ['Service', 'Full service'], ['Drop-off', '16/11/2026, 07:30'], ['Estimate', 'R1 560.00', true]].map(([a, b, bold]) => row(a, b, bold)).join('')), btns(['Confirm', 'Change']), O('Confirm'), I('✅ <b>You’re booked!</b><br>Ref: KR-2026-0214<br>📍 Kloof Road Auto Care, 14 Kloof Road, Sea Point'), btns(['Add to calendar', 'Manage booking']), chip('Sun 15/11/2026'), I('⏰ Reminder: your Corolla is booked in tomorrow at 07:30. Please leave the spare key if you can.', '17:00'), O('Will do, thanks', '17:05')]],
    ['Extra problem found', [chip('Mon 16/11/2026'), I('Hi Sipho, our technician found that your <b>front brake pads are worn thin</b>. Photo below 👇', '10:42'), I('📷 <i>Photo: front brake pads, 2 mm left</i>', '10:42'), I('<b>Quote for extra work</b>' + [['Front brake pads (fitted)', 'R1 380.00', true]].map(([a, b, bold]) => row(a, b, bold)).join('') + 'Adds about 1 hour to the job.', '10:43'), btns(['Approve', 'Decline', 'Call me'])]],
    ['Customer approves', [O('Approve', '10:50'), I('Thanks Sipho, approved ✅ We’ll fit the pads together with the service. Your job card <b>KR-2026-0214</b> has been updated.', '10:50')]],
    ['Status updates', [chip('Mon 16/11/2026'), I('🔧 Your Corolla is <b>in the workshop</b> now.', '08:05'), I('✅ Your Corolla is <b>ready for collection</b>. We’re open until 17:00.', '14:20'), I('<b>Final bill</b>' + [['Full service', 'R1 560.00'], ['Front brake pads', 'R1 380.00'], ['Total', 'R2 940.00', true]].map(([a, b, bold]) => row(a, b, bold)).join(''), '14:20'), btns(['Pay now', 'Pay when I collect']), O('Pay now', '14:31')]],
    ['Payment and thanks', [I('Here is your secure payment link for <b>R2 940.00</b> 💳<br>Pay by card or instant EFT.', '14:31'), btns(['Pay R2 940.00']), I('✅ Payment received. Thank you! Your receipt is attached.', '14:33'), O('Picking it up at 16:30', '14:34'), I('Perfect, the keys will be at the front desk. How was our service? (1–5)', '16:50'), O('5 – Great service', '17:10')]],
    ['Service reminder', [chip('6 months later · 16/05/2027'), I('Hi Sipho, your Corolla is due for its next service at about <b>72 000 km</b> 🔧 Shall we book you in?', '09:00'), btns(['Book a service', 'Remind me later']), O('Book a service', '09:12'), I('Great! I’ll send you the free days at <b>Kloof Road Auto Care</b> 📅', '09:12')]],
  ];`,

  journey: {
    lanes: ['Customer (WhatsApp)', 'WhatsApp bot', 'Workshop systems', 'Workshop team'],
    stages: [['Book', 0, 7], ['Remind', 8, 8], ['Repair and quote', 9, 12], ['Collect and pay', 13, 15], ['Next service', 16, 17]],
    nodes: [
      ['c1', 0, 0, 'start', 'Customer asks to\nbook a service'],
      ['b1', 1, 1, 'step', 'Welcome and\nmain menu'],
      ['c2', 2, 0, 'step', 'Sends make, model,\nyear and reg'],
      ['b2', 3, 1, 'step', 'Asks service type\nand shows slots'],
      ['c3', 4, 0, 'step', 'Picks a drop-off\nslot'],
      ['d1', 5, 2, 'decision', 'Slot still\nfree?'],
      ['b4', 6, 1, 'step', 'Confirms with a\nreference number'],
      ['s2', 7, 2, 'system', 'Create job card and\ncalendar booking'],
      ['b5', 8, 1, 'step', 'Sends the\nday-before reminder'],
      ['t1', 9, 3, 'human', 'Technician finds a\nworn part, takes photo'],
      ['b6', 10, 1, 'step', 'Sends photo and\nquote to approve'],
      ['c5', 11, 0, 'step', 'Approves the\nextra repair'],
      ['t2', 12, 3, 'offline', 'Car is serviced\nand repaired'],
      ['b7', 13, 1, 'step', 'Status updates and\nfinal bill'],
      ['c6', 14, 0, 'step', 'Pays by\npayment link'],
      ['s4', 15, 2, 'system', 'Payment confirmed,\njob card closed'],
      ['b8', 16, 1, 'step', 'Asks for a rating,\nsets service reminder'],
      ['c7', 17, 0, 'end', 'Books next\nservice'],
    ],
    edges: [['c1', 'b1'], ['b1', 'c2'], ['c2', 'b2'], ['b2', 'c3'], ['c3', 'd1'], ['d1', 'b4', 'Yes'], ['d1', 'b2', 'No: offer other times', 'back'], ['b4', 's2'], ['s2', 'b5'], ['b5', 't1'], ['t1', 'b6'], ['b6', 'c5'], ['c5', 't2'], ['t2', 'b7'], ['b7', 'c6'], ['c6', 's4'], ['s4', 'b8'], ['b8', 'c7']],
  },

  requirements: {
    intro: 'This use case needs a workshop system that holds job cards, a calendar for drop-offs, and a way to take payment. Most South African independent workshops start with simple tools, and some workshop systems have no public API, so check each one before you commit.',
    functions: [
      {
        fn: 'Workshop management (job cards and quotes)', why: 'Holds vehicles, job cards, quotes and service history, so the bot can read and update the job.',
        easy: ['A Google Sheet for bookings and job status', 'Free. Staff update one status column and the bot reads it through Make or n8n. Fine for a small workshop, not for stock or invoicing.'],
        ideal: [
          ['Workshop Software (workshopsoftware.com)', 'Cloud job cards, quoting, booking diary, service reminders and Xero sync. Lists South African pricing from about R1 400 per month. Public API or Zapier connector not confirmed. ⚠'],
          ['AUTOMATE or TTN Garage', 'Listed on review sites as garage systems used in South Africa, with job cards and WhatsApp or SMS reminders. API access and prices not verified. ⚠'],
        ],
        note: 'Many local garage systems are closed products. If there is no API, the team can update a shared sheet or the bot can be given a daily export instead. Confirm with each vendor. ⚠',
      },
      {
        fn: 'Bookings and drop-off calendar', why: 'Shows free drop-off slots and holds the booking for the vehicle.',
        easy: ['Google Calendar', 'Free. One calendar per workshop or bay. Works with Zapier, Make and n8n.'],
        ideal: [['Microsoft 365 Bookings', 'Good if the workshop already uses Microsoft 365.'], ['The booking diary inside your workshop system', 'Best, as bookings and job cards stay in one place. Needs an API from the vendor. ⚠']],
      },
      {
        fn: 'Photos and quotes in chat', why: 'The technician sends a photo and a quote, and the customer approves in writing.',
        easy: ['Technician sends the photo to the S10U inbox', 'Stated on S10U’s site: shared inbox with images and files, and hand-over to an agent. The quote can be a typed message with buttons.'],
        ideal: [['Quote created in the workshop system, sent as a PDF', 'Gives a proper quote number and an audit trail. The link to WhatsApp can be made through an API or an automation tool (Make, n8n, Zapier) and should be confirmed with S10U. ⚠']],
        note: 'Keep the “Approve” reply and the time it was sent. It is your proof the customer agreed to the extra work.',
      },
      {
        fn: 'Status updates', why: 'Tells the customer when the car is in the workshop and ready for collection.',
        easy: ['Staff tap a status button in the S10U inbox', 'Stated on S10U’s site: Workflow Builder with buttons and routing. No code. The reply goes out as a WhatsApp message.'],
        ideal: [['Status change in the job card sends the message automatically', 'Needs a webhook or API from the workshop system, or an automation tool. Confirm with the vendor and S10U. ⚠']],
        note: 'Messages sent after 24 hours from the customer’s last message must use Meta-approved templates.',
      },
      payments('Takes payment for the final bill before or when the customer collects.'),
      {
        fn: 'Service reminders', why: 'Reminds the customer about drop-off and the next service by time or distance.',
        easy: ['Scheduled WhatsApp template from a sheet', 'Dates are stored in a sheet and the automation sends a reminder 6 months later. Needs an approved template and opt-in.'],
        ideal: [['Service interval reminders from the workshop system', 'Workshop Software lists automatic service reminders. Others vary. Check that they can trigger WhatsApp, not only email or SMS. ⚠']],
      },
      crm('Remembers each customer, their vehicles and past services.'),
      accounting,
      reviews,
      handover,
    ],
  },
};
