// Cost card settings for the 13 newer use cases. Same fields as tools/costs.mjs.
// How each one was decided (read the chat's message times in uc/<slug>/chat.html):
//   a bot message is a TEMPLATE when the business writes first after the customer's last message is more than 24 hours old,
//   or when it is the first message ever. Everything else is a normal reply (service message).
// All money amounts in "roi" are EXAMPLES the salesman replaces with the customer's own numbers.
export const MORE = {
  'hotel-guest-house': {
    who: 'guest', whoPlural: 'guests', bizNoun: 'guest house', unit: 'stay',
    convLabel: 'Stays booked on WhatsApp per month',
    journeyText: 'Enquiry, rooms, deposit, pre-arrival notes, late checkout and a review request',
    templateExample: 'pre-arrival information',
    windowNote: 'The guest’s first message opens a 24-hour window and the whole booking happens inside it. The arrival notes go out two days before the stay, after the window has closed, so they are templates (two in a row here: put them in one message to pay once). When the guest asks for a late checkout on the day, a new window opens, and the thank-you after check-out falls inside it.',
    templates: [
      { step: 'Before you arrive', n: 0, kind: 'utility', label: 'Pre-arrival message (template)' },
      { step: 'Before you arrive', n: 1, kind: 'utility', label: 'Second pre-arrival message (template). Tip: combine it with the first.' },
    ],
    roi: {
      fee: 4350, feeLabel: 'Average value of a stay (rand) — example from the demo: 3 nights at R1 450', nsLabel: 'Share of enquiries lost to slow replies today — example', nsDefault: 30,
      redLabel: 'Share won back by instant answers and a deposit link — example only', redDefault: 10,
      prevLabel: 'extra stays per month', valueLabel: 'stay value won per month', meetingLine: 'one stay’s value',
      lead: 'Guests often book with whoever answers first. Try the guest house’s own numbers. The stay value, lost enquiries and the lift are examples, not facts.',
      note: 'S10U has published no hospitality result. ⚠ Not counted: late-checkout and extras sales, direct-booking savings against booking-site commission, and the reviews gained.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'Keep to what the stay needs: name, dates, number of guests. Do not ask for ID or passport numbers in chat. Collect them at check-in.',
      'The guest house is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell guests.',
      'The “book direct for 10% off” offer is direct marketing: it needs the guest’s opt-in, and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Start with the deposit link and the arrival message. A paid deposit protects the room, and one arrival template costs a few cents.',
    moreCosts: 'Card fees on the deposit (the payment gateway) are separate.',
  },

  'gym-classes': {
    who: 'member', whoPlural: 'members', bizNoun: 'gym', unit: 'booking',
    convLabel: 'Class bookings on WhatsApp per month',
    journeyText: 'Timetable, a booking, a waiting list, a reminder, a cancellation and a rating',
    templateExample: 'a class reminder',
    windowNote: 'The member starts the chat, so the booking and the waiting list happen inside a 24-hour window. The reminder the evening before is sent after that window has closed, so it is a template. When the member answers, a new window opens: the cancellation, the waiting-list offer and the booking of the free spot are all normal replies. The rating request three days after the class is a template again.',
    templates: [
      { step: 'Reminder', n: 0, kind: 'utility', label: 'Class reminder, sent the day before (template)' },
      { step: 'After the class', n: 0, kind: 'feedback', label: 'Rating request, sent after the class (template)' },
    ],
    roi: {
      fee: 120, feeLabel: 'Value of one filled class spot (rand) — example', nsLabel: 'Share of class spots that go empty from late cancellations or no-shows today — example', nsDefault: 15,
      redLabel: 'Share refilled from the waiting list — example only', redDefault: 40,
      prevLabel: 'spots refilled per month', valueLabel: 'class income recovered per month', meetingLine: 'one class spot',
      lead: 'A cancelled spot can be offered to the waiting list within seconds. Try the gym’s own numbers. The spot value, empty-spot share and refill share are examples, not facts.',
      note: 'S10U has published no gym result. ⚠ Not counted: members kept because it is easy to book, and the reception time saved.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'Membership status and attendance are personal information. Injuries or health notes are special personal information: do not collect them in chat.',
      'The gym is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell members.',
      'Class offers and the next-class nudge need the member’s opt-in, and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Start with reminders and the waiting list. They cost one cheap template each and refill spots that would stay empty.',
    moreCosts: 'Debit-order and card fees for memberships are separate.',
  },

  'vehicle-service': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'workshop', unit: 'service',
    convLabel: 'Services booked on WhatsApp per month',
    journeyText: 'Booking, a reminder, an extra-work quote with a photo, status updates, payment and a next-service reminder',
    templateExample: 'a service reminder',
    windowNote: 'The customer starts the chat, so the booking is inside a window. The reminder the evening before drop-off is a template. When the customer answers, a new window opens and the extra-work photo and quote, the status updates and the payment link are normal replies. The next-service reminder six months later is a template again. A photo or a PDF counts as one message like any other.',
    templates: [
      { step: 'Confirm booking', n: 2, kind: 'utility', label: 'Drop-off reminder, sent the day before (template)' },
      { step: 'Service reminder', n: 0, kind: 'utility', label: 'Next-service reminder, 6 months later (template). Meta may review it as marketing ⚠' },
    ],
    roi: {
      fee: 1380, feeLabel: 'Value of one piece of extra work (rand) — example from the demo: brake pads', nsLabel: 'Share of services where the technician finds extra work — example', nsDefault: 30,
      redLabel: 'Share approved at once because the customer sees a photo and a quote in chat — example only', redDefault: 30,
      prevLabel: 'extra jobs approved per month', valueLabel: 'extra work approved per month', meetingLine: 'one extra job',
      lead: 'A photo and a quote in the chat are easier to approve than a phone call. Try the workshop’s own numbers. The job value and both shares are examples, not facts.',
      note: 'S10U’s automotive study reported more bookings and finance leads for a dealer group (different business, S10U’s own claim). ⚠ Not counted: repeat services from the reminders and the time saved on calls.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A registration number and the owner’s details are personal information. Keep only what the booking needs, and keep photos of the car on the job card.',
      'The workshop is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell customers.',
      'Service-interval reminders are direct marketing if they sell a service: get the customer’s opt-in, with a “stop” option. This is not legal advice.',
    ],
    startTip: 'Start with the quote-in-chat. It is just replies inside the window and it turns found problems into approved work.',
    moreCosts: 'Card fees on the payment link (the payment gateway) are separate.',
  },

  'takeaway-order': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'takeaway', unit: 'order',
    convLabel: 'Orders on WhatsApp per month',
    journeyText: 'Menu, customising, delivery address, payment, status updates and a rating',
    templateExample: 'a delivery update',
    windowNote: 'The customer starts the chat and the whole order, the payment and the delivery updates happen within about an hour, all inside one 24-hour window. So every bot message is a normal reply and no template is needed. A template is only needed if the takeaway writes first, for example a special on a quiet Tuesday (a marketing template).',
    templates: [],
    roi: {
      mode: 'share',
      fee: 174, feeLabel: 'Average order value (rand) — example from the demo', nsLabel: 'Share of WhatsApp orders that would otherwise come through a delivery app — example', nsDefault: 40,
      redLabel: 'Commission the delivery app would take (%) — reported at 20% to 30% ⚠, example', redDefault: 25,
      prevLabel: 'orders moved off delivery apps per month', valueLabel: 'commission kept per month', meetingLine: 'the commission on one app order',
      lead: 'An order that arrives on WhatsApp costs a few rand in messages, not a share of the bill. Try the takeaway’s own numbers. The share and the commission rate are examples, not facts.',
      note: 'Delivery-app commission varies by contract: check the takeaway’s own rate. ⚠ Not counted: drivers, packaging and the lost customer data on app orders.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'An address or a location pin is personal information. Keep it only as long as the delivery needs it, and do not reuse it for marketing without opt-in.',
      'The takeaway is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell customers.',
      '“Want the same order next time?” and specials are direct marketing: they need opt-in and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Put the WhatsApp number on the boxes and the menu. Orders that come straight to you cost a few rand in messages, not a commission.',
    moreCosts: 'Card and EFT fees on the payment link (the payment gateway) and your drivers are separate.',
  },

  'retail-catalogue': {
    who: 'shopper', whoPlural: 'shoppers', bizNoun: 'shop', unit: 'order',
    convLabel: 'Orders on WhatsApp per month',
    journeyText: 'Browsing, a basket, payment, dispatch and delivery notices, a review request and a stock alert',
    templateExample: 'a dispatch notice',
    windowNote: 'The shopper starts the chat and the whole purchase is inside one window. The dispatch notice two days later is a template. When the shopper taps “track my parcel”, a window opens, but the “delivered” notice two days after that is a template again. The review request two days later is a template, and the shopper’s answer opens a window for the stock-alert sign-up.',
    templates: [
      { step: 'Dispatch and delivery', n: 0, kind: 'utility', label: 'Dispatch notice with tracking (template)' },
      { step: 'Dispatch and delivery', n: 2, kind: 'utility', label: 'Delivered notice (template)' },
      { step: 'Review and alerts', n: 0, kind: 'feedback', label: 'Review request, two days after delivery (template)' },
    ],
    roi: {
      fee: 1645, feeLabel: 'Average order value (rand) — example from the demo', nsLabel: 'Share of enquiries that end in an abandoned basket today — example', nsDefault: 60,
      redLabel: 'Share recovered by instant answers and a payment link — example only', redDefault: 10,
      prevLabel: 'abandoned baskets recovered per month', valueLabel: 'sales recovered per month', meetingLine: 'one basket’s value',
      lead: 'A shopper who can ask a question and pay in the same chat is less likely to leave. Try the shop’s own numbers. The order value and both shares are examples, not facts.',
      note: 'S10U’s retail study reported higher conversion for a retailer (the page and the PDF give 15% and 13%): a different business and S10U’s own claim. ⚠ Not counted: repeat sales from back-in-stock alerts.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A delivery address and an order history are personal information. Keep only what the order and the courier need.',
      'The shop is the responsible party. S10U, the AI provider, the courier and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell shoppers.',
      'Back-in-stock and sale alerts are direct marketing: they need opt-in and a “stop” option, as the demo shows. This is not legal advice.',
    ],
    startTip: 'Start with the order notices (paid, dispatched, delivered). They are the cheapest messages and cut “where is my order?” questions.',
    moreCosts: 'Card and EFT fees on the payment link (the payment gateway) and courier costs are separate.',
  },

  'quote-request': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'business', unit: 'job',
    convLabel: 'Quote requests on WhatsApp per month',
    journeyText: 'Photos, a site visit, a quote with a PDF, a deposit, and a sign-off with a review request',
    templateExample: 'a quote notice',
    windowNote: 'The customer starts the chat and answers next morning, so the booking is inside two windows. The “technician is 20 minutes away” message goes out just over 24 hours after the customer’s last message, so it needs a template. The quote arrives the next day, also after the window has closed: the quote notice, the PDF and the summary each need a template (put them in one template with the PDF attached to pay once). When the customer accepts, a window opens for the deposit. The sign-off message two days later is a template.',
    templates: [
      { step: 'After the visit', n: 0, kind: 'utility', label: 'Technician on the way (template)' },
      { step: 'The quote arrives', n: 0, kind: 'utility', label: 'Quote ready (template)' },
      { step: 'The quote arrives', n: 1, kind: 'utility', label: 'Quote PDF, sent before the customer replies (template). Tip: attach it to the first template.' },
      { step: 'The quote arrives', n: 2, kind: 'utility', label: 'Quote summary, sent before the customer replies (template). Tip: put it in the first template.' },
      { step: 'After the job', n: 0, kind: 'feedback', label: 'Job sign-off with a rating request (template)' },
    ],
    roi: {
      fee: 6850, feeLabel: 'Average value of a job (rand) — example from the demo quote', nsLabel: 'Share of enquiries that go cold because nobody replied in time — example', nsDefault: 25,
      redLabel: 'Share won back by instant replies and photos in the chat — example only', redDefault: 20,
      prevLabel: 'extra jobs won per month', valueLabel: 'job value won per month', meetingLine: 'one job’s value',
      lead: 'The business that quotes first often wins the job. Try the business’s own numbers. The job value and both shares are examples, not facts.',
      note: 'S10U has published no trades result. ⚠ Not counted: the office time saved on phone tag, and the reviews gained.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'Photos of a home can show people, documents and the address. Ask for photos of the problem only, and keep them with the job.',
      'The business is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell customers.',
      'The deposit link and quote are service messages. Any “thank you, here is 10% off” is direct marketing: opt-in and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Put the quote and its PDF in one template. One message instead of three cuts the quote cost to a third.',
    moreCosts: 'Card fees on the deposit link (the payment gateway) are separate.',
  },

  'delivery-tracking': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'courier', unit: 'parcel',
    convLabel: 'Parcels tracked on WhatsApp per month',
    journeyText: 'A collection notice, tracking, a changed time slot, a driver alert, proof of delivery, a problem report and a rating',
    templateExample: 'a collection notice',
    windowNote: 'The first message, “your parcel has been collected”, comes from the courier, so it is a template (the courier writes first). The customer’s tap on “track my parcel” opens a window. Each later message arrives within 24 hours of the customer’s last message (the driver alert, the proof of delivery and the rating), so they are normal replies. A parcel that spends longer in transit than 24 hours without a customer message would need another template.',
    templates: [
      { step: 'Parcel collected', n: 0, kind: 'utility', label: 'Parcel collected (template)' },
    ],
    roi: {
      fee: 35, feeLabel: 'Cost of one “where is my parcel?” call or email (rand) — example', nsLabel: 'Share of parcels that trigger a call or email today — example', nsDefault: 30,
      redLabel: 'Share answered by the bot with no person — example only', redDefault: 70,
      prevLabel: 'calls and emails avoided per month', valueLabel: 'support cost saved per month', meetingLine: 'one tracking call',
      lead: 'Most calls to a courier ask where the parcel is. The bot can answer at once, day and night. Try the courier’s own numbers. The cost per call and both shares are examples, not facts.',
      note: 'S10U’s call-centre study reported 20% fewer help-desk calls for one client: a different business and S10U’s own claim. ⚠ Not counted: fewer failed deliveries from the slot changes.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A name, an address and a photo of the doorstep are personal information. Keep proof-of-delivery photos with the waybill, and do not reuse them.',
      'The courier is the responsible party for its customers’ data; the sender may be too. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer.',
      'Delivery notices are service messages. Anything promotional needs opt-in and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Send one collection notice per parcel and let customers ask for the rest. Their questions open a free-to-reply window.',
    moreCosts: 'Courier system and tracking-feed fees are separate.',
  },

  'payment-reminders': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'business', unit: 'customer',
    unitsInDemo: 3,
    convLabel: 'Customers messaged per month',
    journeyText: 'Three customers: an invoice, a reminder, a payment, a balance check, a promise to pay and an overdue hand-over',
    templateExample: 'an invoice notice',
    windowNote: 'This demo follows three customers, so the totals are for all three and the monthly figures use the average per customer. An invoice or a reminder is always sent by the business first, so each one is a template. When a customer answers, a window opens for the receipt and the replies. The closing note to Lindiwe falls within 24 hours of her promise to pay, so it is a normal reply.',
    templates: [
      { step: 'Invoice sent', n: 0, kind: 'utility', label: 'Invoice notice with a pay link (template)' },
      { step: 'Friendly reminder', n: 0, kind: 'utility', label: 'Friendly reminder (template)' },
      { step: 'Promise to pay', n: 0, kind: 'utility', label: 'Overdue reminder (template)' },
      { step: 'Overdue, polite hand-over', n: 0, kind: 'utility', label: 'Overdue notice (template)' },
    ],
    roi: {
      fee: 899, feeLabel: 'Average invoice (rand) — example from the demo', nsLabel: 'Share of invoices paid late today — example', nsDefault: 30,
      redLabel: 'Share of those that now arrive on time — S10U’s financial-services study: late payments down 19%', redDefault: 19,
      prevLabel: 'invoices paid on time instead of late per month', valueLabel: 'cash received sooner per month', meetingLine: 'one invoice',
      lead: 'A pay link in the reminder makes paying a one-tap job. Try the business’s own numbers. The invoice value and the late share are examples, not facts.',
      note: 'The 19% is S10U’s claim for one financial-services client: a different business, not a promise here. ⚠ This is cash that arrives sooner, not extra revenue. Not counted: the staff time saved on calls and statements.',
    },
    privacyTitle: 'Privacy and fair collection (POPIA)',
    privacy: [
      'A balance and a payment history are financial information. Share a balance only after the customer is verified, and never in a group chat.',
      'Keep the tone respectful: no threats, and contact only in reasonable hours. Rules on debt collection and credit may apply: get advice for overdue accounts.',
      'The business is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Every message needs a “stop” option. This is not legal advice.',
    ],
    startTip: 'Start with the invoice notice and one friendly reminder. They are cheap templates and the pay link does the rest.',
    moreCosts: 'Card, EFT and debit-order fees (the payment gateway or bank) are separate.',
  },

  'loyalty-rewards': {
    who: 'member', whoPlural: 'members', bizNoun: 'coffee shop', unit: 'member',
    convLabel: 'Active members messaged per month',
    journeyText: 'Joining with consent, points after a purchase, a balance check, a voucher, a birthday gift and an expiry reminder',
    templateExample: 'a points-earned notice',
    windowNote: 'The member starts the chat by scanning a QR code, so joining is inside a window. The points message after a purchase is a template (it assumes the visit is more than a day after joining). A balance check, a reward and a voucher are the member’s own questions, so they are normal replies. The birthday gift is a marketing template, and the expiry reminder months later is a template again (with the “stop” line as a second message: put it inside the template).',
    templates: [
      { step: 'Earn points', n: 0, kind: 'utility', label: 'Points earned after a purchase (template). A normal reply if the purchase is within a day of joining.' },
      { step: 'Birthday reward', n: 0, kind: 'marketing', label: 'Birthday gift (marketing template)' },
      { step: 'Refer and expiry', n: 1, kind: 'utility', label: 'Points expiry reminder (template). Meta may review it as marketing ⚠' },
      { step: 'Refer and expiry', n: 2, kind: 'utility', label: '“Reply STOP” line, sent as a separate message (template). Tip: put it in the first template.' },
    ],
    roi: {
      fee: 78, feeLabel: 'Average spend per visit (rand) — example from the demo', nsLabel: 'Share of members who are reached by a message in a month — example', nsDefault: 60,
      redLabel: 'Share of those who make one extra visit because of it — example only', redDefault: 10,
      prevLabel: 'extra visits per month', valueLabel: 'extra spend per month', meetingLine: 'one visit',
      lead: 'A birthday gift or an expiring-points reminder brings members back. Try the shop’s own numbers. The spend, the reach and the response are examples, not facts. The result may be modest: a coffee is a small sale.',
      note: 'S10U has published no loyalty result. ⚠ Not counted: members kept longer, and what a member’s data is worth to the shop.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A name, a number and a birthday are personal information. The joining step asks for consent in plain words, as the demo shows. Keep the wording and the date.',
      'The coffee shop is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell members.',
      'Offers, birthday gifts and referrals are direct marketing: every message needs a “stop” option and the opt-in on file. This is not legal advice.',
    ],
    startTip: 'Let members ask for their balance. Their questions are normal replies, and only the birthday and expiry messages are templates.',
    moreCosts: 'The loyalty software or till link, if any, is separate.',
  },

  'feedback-reviews': {
    who: 'customer', whoPlural: 'customers', bizNoun: 'tour company', unit: 'customer',
    unitsInDemo: 2,
    convLabel: 'Customers asked for feedback per month',
    journeyText: 'Two customers: a happy one who leaves a review, and an unhappy one who gets a call from the manager',
    templateExample: 'a feedback request',
    windowNote: 'This demo follows two customers, so the totals are for both and the monthly figures use the average per customer. The feedback request goes out after the tour, so it is a template: the business writes first. When the customer scores, a window opens for the follow-up questions and the review link. The manager’s messages the next morning fall within 24 hours of the customer’s last message, so they are normal replies (and cost the same as a bot reply).',
    templates: [
      { step: 'Feedback request', n: 0, kind: 'feedback', label: 'Feedback request after the tour (template)' },
      { step: 'Unhappy score', n: 0, kind: 'feedback', label: 'Feedback request after the tour (template)' },
    ],
    agentMessages: [{ step: 'Manager follow-up', n: 0 }, { step: 'Manager follow-up', n: 1 }],
    replyLabel: 'Bot and manager replies',
    roi: {
      fee: 900, feeLabel: 'Value of a customer who comes back or recommends (rand) — example', nsLabel: 'Share of customers who are unhappy today — example', nsDefault: 10,
      redLabel: 'Share won back by a quick call from the manager — example only', redDefault: 30,
      prevLabel: 'unhappy customers won back per month', valueLabel: 'value kept per month', meetingLine: 'one returning customer',
      lead: 'An unhappy customer who gets a call the next morning often stays. Try the business’s own numbers. The customer value and both shares are examples, not facts.',
      note: 'S10U’s insurance study reported 87% satisfaction with its WhatsApp assistant: a different business and S10U’s own claim. ⚠ Not counted: the extra Google reviews and bookings that come from happy customers.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A complaint can include names and personal details. Keep it with the booking, and restrict who can read it.',
      'The business is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell customers.',
      'Do not hide the review link from unhappy customers: Google forbids selecting who may review. Every message needs a “stop” option. This is not legal advice.',
    ],
    startTip: 'Send the feedback request while the tour is fresh. One template buys a score, a comment and a review link.',
    moreCosts: 'The review tools, if any, are separate.',
  },

  'event-tickets': {
    who: 'attendee', whoPlural: 'attendees', bizNoun: 'organiser', unit: 'order',
    convLabel: 'Ticket orders on WhatsApp per month',
    journeyText: 'Event info, ticket types, payment, QR tickets, a reminder, a ticket transfer and a survey',
    templateExample: 'an event reminder',
    windowNote: 'The attendee starts the chat, and the purchase, payment and the tickets themselves (sent as separate QR messages) are inside one window. The reminder the day before the event is a template. When the attendee answers, a window opens for the ticket transfer. The survey two days after the event is a template, and the answer opens a window for the early-bird sign-up.',
    templates: [
      { step: 'Reminder', n: 0, kind: 'utility', label: 'Event reminder, sent the day before (template)' },
      { step: 'After the event', n: 0, kind: 'feedback', label: 'Survey after the event (template)' },
    ],
    roi: {
      fee: 2900, feeLabel: 'Average order value (rand) — example from the demo: 2 VIP tickets', nsLabel: 'Share of enquiries that end without a purchase today — example', nsDefault: 70,
      redLabel: 'Share won because the buyer can pay in the chat — example only', redDefault: 5,
      prevLabel: 'extra orders per month', valueLabel: 'ticket sales won per month', meetingLine: 'one order',
      lead: 'A buyer who can ask a question and pay in the same chat is more likely to finish. Try the organiser’s own numbers. The order value and both shares are examples, not facts.',
      note: 'S10U has published no events result. ⚠ Not counted: fewer support calls at the gate, and the 2027 early-bird list.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'An attendee’s name, number and tickets are personal information. A ticket transfer shares a friend’s number: the buyer should confirm the friend agrees.',
      'The organiser is the responsible party. S10U, the ticket platform, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell attendees.',
      'Next year’s early-bird message is direct marketing: it needs opt-in and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Send tickets in the chat the minute the payment lands. The tickets cost normal replies, and the reminder is one cheap template.',
    moreCosts: 'The ticket platform fee and card fees on the payment link are separate.',
  },

  'real-estate-viewing': {
    who: 'buyer', whoPlural: 'buyers', bizNoun: 'agency', unit: 'viewing',
    convLabel: 'Viewing enquiries on WhatsApp per month',
    journeyText: 'The listing, a few questions, similar homes, a viewing, a reminder and feedback',
    templateExample: 'a viewing reminder',
    windowNote: 'The buyer starts the chat from the listing, so the questions, the similar homes and the booking are inside one window. The reminder the afternoon before the viewing is a template. When the buyer answers, a new window opens: the “see you in 1 hour” message the next morning, the late-arrival reply and the feedback request after the viewing are normal replies.',
    templates: [
      { step: 'Directions and reminder', n: 0, kind: 'utility', label: 'Viewing reminder, sent the day before (template)' },
    ],
    roi: {
      fee: 2500, feeLabel: 'Value of one extra viewing to the agency (rand) — example', nsLabel: 'Share of enquiries that never reach a viewing today — example', nsDefault: 60,
      redLabel: 'Share won by instant replies and easy booking — example only', redDefault: 5,
      prevLabel: 'extra viewings per month', valueLabel: 'viewing value won per month', meetingLine: 'one viewing',
      lead: 'A buyer who gets an answer in seconds is more likely to book a viewing. Try the agency’s own numbers. The viewing value and both shares are examples, not facts. A viewing is worth a share of the commission, not the whole of it.',
      note: 'S10U has published no property result. ⚠ Not counted: the agent’s time saved, and enquiries outside office hours.',
    },
    privacyTitle: 'Privacy (POPIA)',
    privacy: [
      'A budget and a bond pre-approval are financial information. The demo only records “yes, not yet or cash”: keep it that way and send detail to the agent.',
      'The agency is the responsible party. S10U, the property portal, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell buyers.',
      '“Similar homes” and later alerts are direct marketing: opt-in and a “stop” option. This is not legal advice.',
    ],
    startTip: 'Answer enquiries in the chat and book the viewing there. Replies are cheap, and the single reminder template protects the agent’s diary.',
    moreCosts: 'Property-portal lead fees are separate.',
  },

  'school-fees': {
    who: 'parent', whoPlural: 'parents', bizNoun: 'school', unit: 'parent chat',
    convLabel: 'Parent chats on WhatsApp per month',
    journeyText: 'Verifying the parent, a fee balance, a payment link, a receipt, a circular with an RSVP and an absence report',
    templateExample: 'a school circular',
    windowNote: 'The parent starts the chat and verifies with a code, so the balance, the payment link and the receipt are inside one window. The Sports Day circular two weeks later is sent by the school, so it is a template. When the parent answers, a window opens for the RSVP. The absence report on another day is the parent’s own message, so the replies are normal.',
    templates: [
      { step: 'School circular', n: 0, kind: 'utility', label: 'School circular (template). Meta may review it as marketing ⚠' },
    ],
    roi: {
      fee: 45, feeLabel: 'Cost of one fee call or email handled by the school office (rand) — example', nsLabel: 'Share of parents who contact the office about fees or news today — example', nsDefault: 40,
      redLabel: 'Share the bot answers without a person — example only', redDefault: 50,
      prevLabel: 'office contacts avoided per month', valueLabel: 'office time saved per month', meetingLine: 'one office contact',
      lead: 'Fee balances, receipts and absence notes are routine questions the bot can answer at once. Try the school’s own numbers. The cost per contact and both shares are examples, not facts.',
      note: 'S10U’s education study reported 98% of an enrolment target and a 92% open rate for one client: a different school and S10U’s own claim. ⚠ Not counted: fees paid sooner because the link is in the chat.',
    },
    privacyTitle: 'Children’s data (POPIA)',
    privacy: [
      'A child’s name, grade and fee account are personal information of a child. Verify the parent first, as the demo does, and share nothing about another family.',
      'The school is the responsible party. S10U, the fee system, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell parents.',
      'Never ask for a child’s ID number or medical details in chat. Every proactive message needs a “stop” option. Get legal sign-off for children’s data. This is not legal advice.',
    ],
    startTip: 'Let parents ask for their balance and pay in the chat. Their questions are normal replies, and the only template is the school’s own circular.',
    moreCosts: 'Card and EFT fees on the payment link (the payment gateway) and the fee-system link are separate.',
  },
  'aesthetic-booking': {
    who: 'client', whoPlural: 'clients', bizNoun: 'clinic', unit: 'appointment',
    journeyText: 'The client chooses the doctor or cosmetologist, taps a time and accepts, then gets a reminder',
    templateExample: 'an appointment reminder',
    windowNote: 'The client starts the chat, so the whole booking happens inside the 24-hour window. The reminder the day before goes out after the window has closed, so it is an approved template. When the client answers, a new window opens and the arrival note is a normal reply.',
    templates: [
      { step: 'Reminder', n: 0, kind: 'utility', label: 'Appointment reminder, sent the day before (template)' },
    ],
    roi: {
      fee: 850, feeLabel: 'Average consultation fee (rand) — example', nsLabel: 'Share of appointments that are no-shows today — example', nsDefault: 12,
      redLabel: 'No-shows prevented by an easy booking and a reminder — example only', redDefault: 28,
      note: 'The 28% is S10U’s reported result for one healthcare client (missed consultations down 28%): a different business and S10U’s own claim. ⚠ Not counted: reception time saved on the phone.',
      lead: 'A booking in four taps and a reminder cut no-shows. Try the clinic’s own numbers. The fee and the no-show rate are examples, not facts.',
      valueLabel: 'fees recovered per month', meetingLine: 'one consultation fee',
    },
    privacyTitle: 'Health information (POPIA)',
    privacy: [
      'Health and treatment records are special personal information. The bot collects booking details only: name, time and who the client will see. It gives no clinical advice.',
      'The clinic is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell clients.',
      'Add a short privacy notice and a “stop” option at booking. Get legal sign-off before going live. This is not legal advice.',
    ],
    startTip: 'Start with the four-tap booking and the reminder. The booking is just replies inside the window, and the reminder is one cheap template.',
    moreCosts: 'Card fees on any deposit paid by payment link (the payment gateway) are separate.',
  },
  'aesthetic-reschedule': {
    who: 'client', whoPlural: 'clients', bizNoun: 'clinic', unit: 'appointment',
    journeyText: 'The client asks to move her appointment, taps a new time and accepts, then gets a reminder and a rating request',
    templateExample: 'an appointment reminder',
    windowNote: 'The client starts the chat, so the whole change happens inside the 24-hour window. The reminder the day before goes out after the window has closed, so it is an approved template. When the client answers, a new window opens and the arrival note and the rating request are normal replies.',
    templates: [
      { step: 'Reminder', n: 0, kind: 'utility', label: 'Appointment reminder, sent the day before (template)' },
    ],
    roi: {
      fee: 850, feeLabel: 'Average consultation fee (rand) — example', nsLabel: 'Share of appointments that are no-shows today — example', nsDefault: 12,
      redLabel: 'No-shows prevented by an easy booking and a reminder — example only', redDefault: 28,
      note: 'The 28% is S10U’s reported result for one healthcare client (missed consultations down 28%): a different business and S10U’s own claim. ⚠ Not counted: reception time saved on the phone.',
      lead: 'An easy change keeps the slot full: a client who can move in three taps does not simply fail to come. Try the clinic’s own numbers. The fee and the no-show rate are examples, not facts.',
      valueLabel: 'fees recovered per month', meetingLine: 'one consultation fee',
    },
    privacyTitle: 'Health information (POPIA)',
    privacy: [
      'Health and treatment records are special personal information. The bot collects booking details only: name, time and who the client will see. It gives no clinical advice.',
      'The clinic is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell clients.',
      'Add a short privacy notice and a “stop” option at booking. Get legal sign-off before going live. This is not legal advice.',
    ],
    startTip: 'Start with the move-in-three-taps flow. It is just replies inside the window, and the reminder is one cheap template.',
    moreCosts: 'Card fees on any deposit paid by payment link (the payment gateway) are separate.',
  },
  'aesthetic-support': {
    who: 'client', whoPlural: 'clients', bizNoun: 'clinic', unit: 'support chat',
    convLabel: 'Support chats on WhatsApp per month',
    journeyText: 'Appointment lookup, a care-protocol PDF, FAQ answers, doctor-approved answers, a question for the doctor and an urgent hand-over to reception',
    templateExample: 'a doctor’s answer after the window closed',
    windowNote: 'The client’s first message opens a 24-hour window, and this whole chat happens in one day inside it. So every reply is a normal reply and no template is needed. The doctor’s answer and the receptionist’s message are typed by people and are charged like other replies. If the doctor answered the next day, after the window closed, that answer would have to be a template. The AI assistant’s own running cost (the AI model) is separate and is not in this table.',
    templates: [],
    agentMessages: [{ step: 'Doctor answers', n: 0 }, { step: 'Urgent: reception', n: 1 }],
    replyLabel: 'Bot, doctor and receptionist replies',
    roi: {
      fee: 60, feeLabel: 'Cost of one question handled by reception by phone or message (rand) — example', nsLabel: 'Share of these questions that would otherwise reach reception — example', nsDefault: 80,
      redLabel: 'Share the assistant answers without a person (appointments, protocols, FAQ, approved answers) — example only', redDefault: 50,
      prevLabel: 'questions the assistant handles per month', valueLabel: 'reception time saved per month', meetingLine: 'what one reception-handled question costs the clinic',
      lead: 'Every question the assistant answers is one less call or message for reception, and the doctor only sees the questions that need a doctor. Try the clinic’s own numbers. The cost per question and the shares are examples, not facts.',
      note: 'The 50% is a placeholder for the clinic to replace. ⚠ Not counted: the AI model cost, the doctor’s time, and fewer missed questions outside office hours.',
    },
    privacyTitle: 'Health information (POPIA)',
    privacy: [
      'Health and treatment records are special personal information. The assistant sends only content the clinic and the doctor have approved. It gives no clinical advice of its own and it hands over to a person when unsure.',
      'The clinic is the responsible party. S10U, the AI provider and Meta are operators and need written agreements. Overseas AI is a cross-border transfer: tell clients.',
      'Care-protocol PDFs and photos sent in chat are health information. Send them only to the right client, keep a “stop” option, and get legal sign-off before going live. This is not legal advice.',
    ],
    startTip: 'Start with My Appointments and the care-protocol PDF. They are the most common questions and they are normal replies inside the window.',
    moreCosts: 'The AI model cost and any extra S10U licence fees are separate.',
  },
};
