// Master guide: what to connect, by type of tool. Easy option first, then ideal options.
// Built from the per-use-case research (tools/cases, tools/requirements.mjs) and the S10U research (tools/s10u-facts.mjs).
// Popularity is our judgement for South African small businesses, not measured market share.
// ⚠ = API access, price or availability was not verified. Update this file when S10U answers.
export const CHECKED = '7 October 2026';

// short names used in "Used in" links: slug -> label
export const CASES = {
  'restaurant-booking': 'Restaurant', 'doctors-appointment': 'Doctor', 'customer-support': 'Support', 'lead-capture': 'Lead capture',
  'salon-booking': 'Salon', 'hotel-guest-house': 'Hotel', 'gym-classes': 'Gym', 'vehicle-service': 'Vehicle service',
  'takeaway-order': 'Takeaway', 'retail-catalogue': 'Retail', 'quote-request': 'Quotes', 'delivery-tracking': 'Delivery',
  'payment-reminders': 'Payments', 'loyalty-rewards': 'Loyalty', 'feedback-reviews': 'Feedback', 'event-tickets': 'Events',
  'real-estate-viewing': 'Property', 'school-fees': 'School',
};
const ALL = Object.keys(CASES);

export const SECTIONS = [
  { id: 'booking', title: 'Bookings and calendars', items: [
    { title: 'Calendars and appointment booking', why: 'Free times, booking slots and reminders.', used: ['restaurant-booking', 'doctors-appointment', 'lead-capture', 'salon-booking', 'hotel-guest-house', 'gym-classes', 'vehicle-service', 'quote-request', 'real-estate-viewing', 'school-fees'],
      easy: ['Google Calendar', 'Free, with an API and push notifications. Works everywhere in South Africa. One calendar per person or room.'],
      ideal: [['Microsoft 365 / Outlook (Graph API)', 'Common in South African firms. Local resellers bill in rand. Works with Make and Zapier.'], ['Calendly', 'Easy booking pages with an API and Zapier. Billed in US dollars.'], ['Cal.com', 'Open source with an API and webhooks. Can be self-hosted.']] },
    { title: 'Restaurant table management', why: 'Tables, covers and reservations.', used: ['restaurant-booking', 'takeaway-order'],
      easy: ['Google Calendar or a Google Sheet', 'The bot writes the booking, staff confirm it.'],
      ideal: [['Dineplan', 'The South African leader, and the only local platform with Reserve with Google. Its API is read-only (GET), so the bot can read bookings but cannot create them. Keys on request, API fee about R190 a month ex VAT per account (check). ⚠']] },
    { title: 'Doctor and practice management', why: 'Patient diaries, files and medical-aid claims.', used: ['doctors-appointment'],
      easy: ['A shared Google Calendar per doctor', 'Staff confirm every booking. Good for a demo or a small practice.'],
      ideal: [['GoodX, Elixir or Healthbridge', 'The real diaries in South African practices. Integration is usually by vendor partnership, not a self-serve API. ⚠'], ['MediSwitch, MediKredit, Healthbridge (claims switches)', 'Claims go through the practice software, not straight from the chat. ⚠']] },
    { title: 'Salon and beauty booking software', why: 'Stylists, services, deposits and rebooking.', used: ['salon-booking'],
      easy: ['One Google Calendar per stylist', 'Free and reliable for a demo.'],
      ideal: [['Fresha', 'Free to start and popular. Its API may be limited or partner-only. ⚠'], ['Booksy', 'Available in South Africa in rand. API access to check. ⚠']] },
    { title: 'Hotel and guest-house booking', why: 'Rooms, rates, and booking sites.', used: ['hotel-guest-house'],
      easy: ['Google Calendar per room, with iCal sync to Airbnb and Booking.com', 'Cheap and simple for a few rooms.'],
      ideal: [['NightsBridge', 'A South African booking and channel-management system. Check for an API or channel links. ⚠'], ['Resly', 'Booking software for accommodation. Check API access. ⚠']] },
    { title: 'Gym and studio software', why: 'Classes, members, waiting lists and debit orders.', used: ['gym-classes'],
      easy: ['Google Sheet or Calendar for the timetable and members', 'Fine for a pilot.'],
      ideal: [['Octiv Fitness or Itensity', 'South African gym management tools. Check for an API. ⚠'], ['Mindbody, Glofox or Wodify', 'International options with APIs. Check local billing. ⚠']] },
    { title: 'Workshop and garage software', why: 'Job cards, quotes and vehicle history.', used: ['vehicle-service'],
      easy: ['A Google Sheet for bookings and job status', 'Staff update the status with buttons in the inbox.'],
      ideal: [['Workshop Software, AUTOMATE or TTN Garage', 'Found in South African workshops. None has a verified API or Zapier link. ⚠']] },
    { title: 'Event ticketing', why: 'Ticket sales, QR tickets and gate scanning.', used: ['event-tickets'],
      easy: ['Link to your ticket platform’s event page', 'Send the ticket link or PDF in WhatsApp.'],
      ideal: [['Howler', 'A public API was found for Howler Tickets.'], ['Quicket, Webtickets or Computicket Box Office', 'Popular in South Africa. No public API found. ⚠']] },
    { title: 'Property and estate agency', why: 'Listings, leads and viewings.', used: ['real-estate-viewing'],
      easy: ['A “WhatsApp the agent” link with the listing reference, plus Google Calendar', 'Leads from Property24 and Private Property can arrive by email.'],
      ideal: [['PropData / PropCon or Entegral', 'Agency software. Check for lead export or an API. ⚠']] },
    { title: 'School administration and fees', why: 'Parents, fee balances, circulars and absences.', used: ['school-fees'],
      easy: ['An exported fee list (CSV or Google Sheet) updated by the bursar', 'The bot reads it after verifying the parent.'],
      ideal: [['D6 (d6+ and D6 Communicator), SchoolSpeak or Edupac', 'Common school systems. Only D6’s communication, admin and payment features were confirmed. API access to check. ⚠']] },
  ] },
  { id: 'customers', title: 'Customers and sales', items: [
    { title: 'CRM (customer records)', why: 'Remember each customer, score leads and trigger follow-ups.', used: ALL.filter(s => !['school-fees', 'event-tickets'].includes(s)),
      easy: ['HubSpot Free CRM', 'The best API and webhooks of the free options. Works with Zapier and Make. Billed in USD or EUR.'],
      ideal: [['Zoho CRM', 'The cost-sensitive South African favourite: local presence, rand billing, API and connectors.'], ['HubSpot Starter or Pro', 'More automation as the team grows.'], ['Salesforce', 'For larger firms.'], ['S10U CRM', 'S10U’s own CRM, built on SuiteCRM, with a REST API. Ask how it links to AI Studio.']] },
    { title: 'Help desk and tickets', why: 'Track problems and who solved them.', used: ['customer-support', 'delivery-tracking'],
      easy: ['Freshdesk (free tier)', 'API, webhooks and Zapier. A Google Sheet can be a ticket log for a demo.'],
      ideal: [['Zendesk', 'The broadest API. Billed in USD.'], ['Zoho Desk', 'Rand-friendly.'], ['HubSpot Service Hub', 'If you already use HubSpot.']] },
    { title: 'Where leads come from', why: 'The first message in WhatsApp.', used: ['lead-capture', 'real-estate-viewing', 'loyalty-rewards', 'event-tickets'],
      easy: ['Click-to-WhatsApp ads on Facebook and Instagram', 'Meta gives a free 72-hour messaging window after a click, if you reply within 24 hours.'],
      ideal: [['QR codes and wa.me links with a pre-filled message', 'Free. Use a different code per shop, flyer or listing.'], ['Web forms into Make or n8n', 'The form posts to an automation that opens the chat. ⚠'], ['Google Ads message extensions', 'Check availability for your account. ⚠']] },
    { title: 'Surveys and feedback forms', why: 'Collect scores and comments.', used: ['feedback-reviews', 'event-tickets'],
      easy: ['In-chat rating saved to Google Sheets', 'No extra tool.'],
      ideal: [['Typeform or Tally', 'Better forms and charts.'], ['A CRM record', 'Keeps the score with the customer.']] },
  ] },
  { id: 'data', title: 'Data and automation', items: [
    { title: 'Spreadsheets (Google Sheets)', why: 'The simplest place to keep lists: menus, members, orders, points.', used: ALL,
      easy: ['Google Sheets', 'Free. Almost every demo can start here. Connects through Zapier, Make or n8n.'],
      ideal: [['Airtable', 'A friendlier database with forms and an API. Billed in USD. ⚠'], ['A proper database or your own system', 'When volume grows or data is sensitive.']] },
    { title: 'Automation tools (the glue)', why: 'Connect S10U to tools that have no ready connector.', used: ALL,
      easy: ['Zapier', 'The simplest, priced in USD. Good for first links.'],
      ideal: [['Make', 'Cheaper and more flexible than Zapier.'], ['n8n', 'Can be self-hosted, so data stays under your control (helps with POPIA).']] },
    { title: 'APIs and webhooks', why: 'How one system tells another that something happened.', used: ALL,
      easy: ['S10U’s own integrations', 'S10U says it has 80+ integrations by category, but does not name them. Ask for the list.'],
      ideal: [['S10U API and webhooks', 'S10U names OAuth 2.0, API keys and signed webhooks. No public docs yet. Ask for them.'], ['S10U custom development', 'For a system with no ready connector. Ask for cost and time.'], ['Meta WhatsApp Cloud API', 'The layer underneath S10U. You normally do not call it yourself.']] },
  ] },
  { id: 'money', title: 'Money', items: [
    { title: 'Payment gateways and links', why: 'Take deposits, bills and orders by payment link in the chat.', used: ALL.filter(s => !['feedback-reviews', 'loyalty-rewards'].includes(s)),
      easy: ['Yoco payment links', 'No code. Money settles in South Africa. Send the link in WhatsApp.'],
      ideal: [['Paystack', 'Stripe-owned, launched in South Africa in 2021. API, webhooks, payment links, cards and bank transfer.'], ['Ozow', 'Instant EFT with an API.'], ['PayFast', 'Long-standing South African gateway with callbacks and plugins.'], ['Peach Payments', 'For larger merchants.']],
      note: 'Stripe itself is not generally open to South African businesses. S10U lists in-chat payments (cards, EFT, vouchers) but does not say which gateways. Native WhatsApp payments are not available in South Africa. ⚠' },
    { title: 'Debit orders and recurring payments', why: 'Memberships, subscriptions and school fees.', used: ['gym-classes', 'payment-reminders', 'school-fees'],
      easy: ['Card on file with recurring billing', 'Simple to start.'],
      ideal: [['A DebiCheck collections provider', 'The bank-approved way to debit accounts. Check providers and fees. ⚠'], ['Paystack or PayFast recurring options', 'Check support for your case. ⚠']] },
    { title: 'Accounting and ERP', why: 'Invoices, quotes, receipts and your books.', used: ['restaurant-booking', 'customer-support', 'lead-capture', 'hotel-guest-house', 'quote-request', 'payment-reminders', 'school-fees'],
      easy: ['Xero', 'Very popular with South African small businesses. Rand, local bank feeds, open API and webhooks. S10U’s blog says it connects Xero and Sage.'],
      ideal: [['Sage Business Cloud Accounting', 'South African-origin, with a REST API. (Sage 50 and Pastel on the desktop have weaker APIs.)'], ['QuickBooks Online or Zoho Books', 'Common alternatives.'], ['Larger ERP systems', 'S10U lists “ERP” as an integration category. Ask which systems.']] },
    { title: 'Point of sale (POS)', why: 'Orders, sales and loyalty at the till.', used: ['restaurant-booking', 'takeaway-order', 'loyalty-rewards'],
      easy: ['Orders by email or a Google Sheet to the kitchen', 'No system link needed.'],
      ideal: [['Lightspeed Restaurant', 'Has an API.'], ['Yoco POS', 'Popular with small businesses. API openness to check. ⚠']] },
  ] },
  { id: 'shop', title: 'Shops and delivery', items: [
    { title: 'E-commerce platforms', why: 'Products, stock, orders and checkout.', used: ['retail-catalogue', 'customer-support', 'takeaway-order'],
      easy: ['WooCommerce', 'REST API and webhooks. Probably the most common small-shop platform in South Africa (no market-share data). Many local plugins.'],
      ideal: [['Shopify', 'The best API and app ecosystem. Rand supported.'], ['Meta Commerce Manager catalogue', 'Shows your products inside WhatsApp. Connects to Shopify and WooCommerce. Check S10U support. ⚠'], ['Takealot seller portal', 'If you sell on the marketplace. ⚠']] },
    { title: 'Couriers and delivery tracking', why: 'Labels, tracking and delivery notices.', used: ['customer-support', 'retail-catalogue', 'delivery-tracking', 'takeaway-order'],
      easy: ['The Courier Guy (Ship Logic)', 'API for quotes, shipments, labels, tracking and webhooks. Sandbox available. WooCommerce plugin.'],
      ideal: [['Ship Logic V2 API directly', 'Full control of labels and tracking.'], ['Bob Go', 'Compares several couriers. Check API. ⚠'], ['Aramex, PUDO, Pargo, Dawn Wing, RAM', 'Check each API. Some are partner-only. ⚠'], ['Mr D Food and Uber Eats (food delivery)', 'Commission reported at 20% to 30%. ⚠']] },
  ] },
  { id: 'reputation', title: 'Reviews and reputation', items: [
    { title: 'Google reviews', why: 'Ask happy customers to review you, and answer reviews.', used: ['restaurant-booking', 'doctors-appointment', 'customer-support', 'salon-booking', 'hotel-guest-house', 'vehicle-service', 'quote-request', 'feedback-reviews', 'real-estate-viewing'],
      easy: ['Google Business Profile review link or QR code', 'Free. Send the link in WhatsApp right after the visit.'],
      ideal: [['Google Business Profile API', 'Read and reply to reviews from your own system. Needs Google approval and quota. ⚠']],
      note: 'Do not only ask happy customers for reviews. Google forbids that (“review gating”). The feedback demo sends unhappy customers to a manager but still lets anyone review.' },
    { title: 'Hellopeter', why: 'The South African customer-service reputation site.', used: ['feedback-reviews', 'delivery-tracking', 'customer-support'],
      easy: ['Hellopeter Review Invites', 'Send customers an invite link. ⚠'],
      ideal: [['Hellopeter business plan with API', 'Check what is included and whether an API exists. ⚠']] },
  ] },
  { id: 'ai', title: 'AI and the platform', items: [
    { title: 'AI providers', why: 'The model that writes the replies.', used: ALL,
      easy: ['OpenAI GPT-4o through S10U (stated on its site)', 'Already part of the platform, so nothing extra to set up.'],
      ideal: [['A private or fine-tuned model (S10U lists both)', 'For health, finance or children’s data. Ask how it works and where chat text is processed.'], ['Other providers (Google Gemini, Anthropic Claude)', 'Reachable from South Africa and billed in USD. Ask S10U whether you can bring your own key. ⚠']],
      note: 'Sending chat text to an overseas AI model is a cross-border transfer under POPIA. Tell customers and use a data processing agreement.' },
    { title: 'MCP (Model Context Protocol)', why: 'A standard way for an AI to use your tools, such as “read this calendar”.', used: [],
      easy: ['Start without it', 'S10U’s API, webhooks and 80+ integrations are the route to try first. S10U does not mention MCP.'],
      ideal: [['Tools that offer MCP servers', 'For example Zapier, HubSpot, Xero, Stripe, Shopify and Google Workspace. Confirm current status before promising it. ⚠'], ['Ask S10U whether MCP is planned', 'Then AI Studio could call your tools directly.']] },
    { title: 'Knowledge for the bot', why: 'The bot answers only from what you give it.', used: ALL,
      easy: ['Upload FAQs, price lists, menus and policies to AI Studio', 'S10U says the chatbot is trained on your content through an editable training screen, in 11 languages.'],
      ideal: [['One maintained source of truth', 'A help centre or guest guide that you update, then re-train when it changes.']] },
    { title: 'WhatsApp Business Platform', why: 'The WhatsApp layer under S10U.', used: ALL,
      easy: ['Let S10U handle it', 'S10U is a Meta Business Partner (its own claim). It sets up the account, number and templates with you.'],
      ideal: [['Know the rules', '24-hour window, approved templates, opt-in, sending limits, and Meta’s rules for AI bots. See the S10U facts page.']] },
  ] },
  { id: 'privacy', title: 'Privacy', items: [
    { title: 'POPIA (South Africa’s privacy law)', why: 'Rules for collecting and using personal information in chat.', used: ALL,
      easy: ['A short privacy notice in the first chat, plus a STOP option', 'Say why you collect data, and let people opt out.'],
      ideal: [['Operator agreements with S10U, the AI provider and any automation tool', 'You are the responsible party. They are operators.'], ['Extra care for health, money and children’s data', 'Collect booking details only. Verify the parent or patient before sharing anything.'], ['Legal sign-off', 'For medical, financial and school customers.']],
      note: 'This is a checklist, not legal advice.' },
  ] },
];
