// Guest journey diagram data (demo 4) for each use case except the restaurant (which has a hand-drawn one).
// lanes: top-to-bottom swim lanes. stages: [label, firstCol, lastCol]. nodes: [id, col, lane, type, label].
// types: start | step | system | decision | human | offline | end. edges: [from, to, label?, 'back'?]
export const JOURNEYS = {
  'doctors-appointment': {
    lanes: ['Patient (WhatsApp)', 'WhatsApp bot', 'Practice systems', 'Reception'],
    stages: [['Book', 0, 6], ['Confirm', 7, 10], ['Remind', 11, 12], ['Visit', 13, 13], ['After', 14, 15]],
    nodes: [
      ['p1', 0, 0, 'start', 'Patient messages\nthe practice'],
      ['b1', 1, 1, 'step', 'Welcome and\nmain menu'],
      ['p2', 2, 0, 'step', 'Chooses visit type\nand doctor'],
      ['b2', 3, 1, 'step', 'Asks which day\nsuits'],
      ['s1', 4, 2, 'system', 'Check the doctor’s\ndiary for free slots'],
      ['b3', 5, 1, 'step', 'Shows free\ntimes'],
      ['p3', 6, 0, 'step', 'Picks a time'],
      ['b4', 7, 1, 'step', 'Asks name and\nhow they pay'],
      ['s2', 8, 2, 'decision', 'Slot still\nfree?'],
      ['b5', 9, 1, 'step', 'Confirms with a\nreference number'],
      ['s3', 10, 2, 'system', 'Save the appointment\nin the diary'],
      ['p4', 10, 0, 'step', 'Receives the\nconfirmation'],
      ['b6', 11, 1, 'step', 'Sends reminders\n(day before, morning)'],
      ['p5', 12, 0, 'step', 'Confirms, moves\nor cancels'],
      ['r1', 12, 3, 'human', 'Reception sees\nchanges in the inbox'],
      ['v1', 13, 3, 'offline', 'Patient arrives and\nsees the doctor'],
      ['b7', 14, 1, 'step', 'Asks for a rating,\noffers a follow-up'],
      ['p6', 15, 0, 'end', 'Rates the visit'],
    ],
    edges: [['p1', 'b1'], ['b1', 'p2'], ['p2', 'b2'], ['b2', 's1'], ['s1', 'b3'], ['b3', 'p3'], ['p3', 'b4'], ['b4', 's2'], ['s2', 'b5', 'Yes'], ['s2', 'b3', 'No: offer other times', 'back'], ['b5', 's3'], ['b5', 'p4'], ['s3', 'b6'], ['b6', 'p5'], ['p5', 'r1'], ['r1', 'v1'], ['v1', 'b7'], ['b7', 'p6']],
  },
  'customer-support': {
    lanes: ['Customer (WhatsApp)', 'WhatsApp bot + AI', 'Business systems', 'Support agent'],
    stages: [['Ask', 0, 4], ['Look up', 5, 7], ['Resolve', 8, 11], ['Close', 12, 15]],
    nodes: [
      ['c1', 0, 0, 'start', 'Customer needs\nhelp'],
      ['b1', 1, 1, 'step', 'Greets and\nshows the menu'],
      ['c2', 2, 0, 'step', 'Picks “Returns\nand refunds”'],
      ['b2', 3, 1, 'step', 'AI answers from\nthe knowledge base'],
      ['d1', 4, 0, 'decision', 'Needs more\nhelp?'],
      ['b3', 5, 1, 'step', 'Asks for the\norder number'],
      ['s1', 6, 2, 'system', 'Look up the order\nin the shop system'],
      ['b4', 7, 1, 'step', 'Shows the order\nstatus'],
      ['c3', 8, 0, 'step', 'Starts a return\n(item and reason)'],
      ['d2', 9, 1, 'decision', 'Can the bot\nfinish this?'],
      ['s2', 10, 2, 'system', 'Create the\nreturn label'],
      ['a1', 10, 3, 'human', 'Agent takes over\nwith the full chat'],
      ['a2', 11, 3, 'human', 'Agent swaps the\nsize and confirms'],
      ['b5', 12, 1, 'step', 'Sends confirmation\nand return label'],
      ['c4', 13, 0, 'step', 'Gets the exchange'],
      ['b6', 14, 1, 'step', 'Asks for a\nrating'],
      ['c5', 15, 0, 'end', 'Rates the chat'],
    ],
    edges: [['c1', 'b1'], ['b1', 'c2'], ['c2', 'b2'], ['b2', 'd1'], ['d1', 'b3', 'Yes'], ['b3', 's1'], ['s1', 'b4'], ['b4', 'c3'], ['c3', 'd2'], ['d2', 's2', 'Yes'], ['d2', 'a1', 'No'], ['a1', 'a2'], ['s2', 'b5'], ['a2', 'b5'], ['b5', 'c4'], ['c4', 'b6'], ['b6', 'c5']],
  },
  'lead-capture': {
    lanes: ['Customer (WhatsApp)', 'WhatsApp bot', 'CRM and calendar', 'Sales advisor'],
    stages: [['Ad', 0, 1], ['Qualify', 2, 5], ['Book', 6, 9], ['Follow up', 10, 14]],
    nodes: [
      ['ad', 0, 0, 'start', 'Taps the\nWhatsApp ad'],
      ['b1', 1, 1, 'step', 'Welcome and\nconsent to chat'],
      ['c1', 2, 0, 'step', 'Answers: owner?\nbill size?'],
      ['b2', 3, 1, 'step', 'Asks suburb,\nroof and photo'],
      ['c2', 4, 0, 'step', 'Sends details\nand a photo'],
      ['s1', 5, 2, 'system', 'Save the lead and\nscore it in the CRM'],
      ['b3', 6, 1, 'step', 'Gives an instant\nestimate, offers a call'],
      ['c3', 7, 0, 'step', 'Picks a time'],
      ['s2', 8, 2, 'system', 'Book the call in\nthe calendar'],
      ['b4', 9, 1, 'step', 'Confirms the call'],
      ['a1', 9, 3, 'human', 'Advisor gets an alert\nwith the summary'],
      ['b5', 10, 1, 'step', 'Reminds on the\nday of the call'],
      ['a2', 11, 3, 'human', 'Advisor calls and\nsends the quote'],
      ['c4', 12, 0, 'step', 'Receives the quote\non WhatsApp'],
      ['c5', 13, 0, 'end', 'Accepts the quote'],
    ],
    edges: [['ad', 'b1'], ['b1', 'c1'], ['c1', 'b2'], ['b2', 'c2'], ['c2', 's1'], ['s1', 'b3'], ['b3', 'c3'], ['c3', 's2'], ['s2', 'b4'], ['b4', 'a1'], ['a1', 'b5'], ['b5', 'a2'], ['a2', 'c4'], ['c4', 'c5']],
  },
  'salon-booking': {
    lanes: ['Client (WhatsApp)', 'WhatsApp bot', 'Booking systems', 'Salon team'],
    stages: [['Book', 0, 6], ['Pay', 7, 9], ['Confirm', 10, 11], ['Remind', 12, 13], ['After', 14, 16]],
    nodes: [
      ['c1', 0, 0, 'start', 'Client messages\nthe salon'],
      ['b1', 1, 1, 'step', 'Welcome and\nmenu'],
      ['c2', 2, 0, 'step', 'Chooses service\nand add-ons'],
      ['b2', 3, 1, 'step', 'Shows the\nstylists'],
      ['c3', 4, 0, 'step', 'Picks a stylist'],
      ['s1', 5, 2, 'system', 'Check the stylist’s\ncalendar'],
      ['b3', 6, 1, 'step', 'Shows free\ntimes'],
      ['c4', 7, 0, 'step', 'Picks a time'],
      ['b4', 8, 1, 'step', 'Asks for a\nR100 deposit'],
      ['s2', 9, 2, 'system', 'Take payment\n(payment link)'],
      ['d1', 10, 2, 'decision', 'Deposit\npaid?'],
      ['b5', 11, 1, 'step', 'Confirms with a\nreference number'],
      ['s3', 12, 2, 'system', 'Save the booking in\nthe salon calendar'],
      ['t1', 12, 3, 'human', 'Stylist sees the\nbooking'],
      ['c5', 12, 0, 'step', 'Receives the\nconfirmation'],
      ['b6', 13, 1, 'step', 'Reminds 24 h and\n1 h before'],
      ['v1', 14, 3, 'offline', 'Client visits\nthe salon'],
      ['b7', 15, 1, 'step', 'Asks for a review,\noffers to rebook'],
      ['c6', 16, 0, 'end', 'Rates and\nrebooks'],
    ],
    edges: [['c1', 'b1'], ['b1', 'c2'], ['c2', 'b2'], ['b2', 'c3'], ['c3', 's1'], ['s1', 'b3'], ['b3', 'c4'], ['c4', 'b4'], ['b4', 's2'], ['s2', 'd1'], ['d1', 'b5', 'Yes'], ['d1', 'b4', 'No: resend link', 'back'], ['b5', 's3'], ['b5', 'c5'], ['s3', 't1'], ['s3', 'b6'], ['b6', 'v1'], ['v1', 'b7'], ['b7', 'c6']],
  },
};
