// Content for demo 5: "What you need to make this work" (one page per use case).
// Sources: S10U site (s10u.co.za, read 7 Oct 2026) and South African tool research (7 Oct 2026).
// ⚠ = needs a check with the vendor (API access, price, or availability was not verified).
export const COMMON = {
  checked: '7 October 2026',
  basics: [
    ['A Meta Business account', 'The WhatsApp Business Platform sits under Meta. S10U is a Meta Business Partner (shown on its site).'],
    ['A phone number that is not already on WhatsApp', 'A dedicated number, ideally the number customers already know. Moving a number off the normal WhatsApp app needs care.'],
    ['A business display name', 'For example “{biz}”. Meta checks it against your real brand.'],
    ['Business verification (and a green tick, optional)', 'Meta verifies the business. The green tick is Meta’s decision, not guaranteed.'],
    ['Approved message templates', 'Free-form replies are allowed for 24 hours after the customer’s last message. Outside that window only pre-approved templates can be sent (reminders, rebooking nudges).'],
    ['Opt-in and opt-out', 'Get permission before you message first, and make stopping easy (S10U lists automatic opt-out handling).'],
    ['Your content to train the bot', 'FAQs, price list, menu or service list, opening hours, policies. The bot can only answer from what you give it.'],
    ['A list of systems to connect', 'Calendar, CRM, payments and so on. The tables on this page show easy and ideal options.'],
    ['A hand-over plan', 'Who answers when the bot cannot, and during which hours. S10U has an inbox with agent hand-over.'],
  ],
  s10uStated: [
    'Workflow Builder: drag-and-drop, no code. Menus, buttons, carousels and routing, with links to external events such as CRM and booking platforms.',
    'AI chatbots trained on your FAQs, product info and manuals, in 11 languages, with hand-over to a live agent.',
    'Shared inbox for WhatsApp, web and in-app chats: assignment, escalation, sentiment, images, locations and files.',
    'Broadcast campaigns with scheduling, link tracking, templates and automatic opt-out.',
    'In-chat payment requests and hosted checkout: cards, EFT and vouchers.',
    'Customer data stored on South African servers (AWS Cape Town). 99.5% uptime target. Email support Monday to Friday, 9:00 to 17:00.',
  ],
  s10uQuestions: [
    'Which systems does AI Studio connect to out of the box (Google Calendar, Google Sheets, a CRM, a booking tool, payment gateways)? The site only says “CRM and booking platforms”.',
    'Is there an API or webhook for custom connections, and where is it documented?',
    'Can we connect Zapier, Make or n8n? Is there MCP support?',
    'Which AI models does AI Studio use? Can we bring our own AI key?',
    'What is the pricing, and what does Meta charge on top per message?',
    'Is the web chat widget included, and is Instagram or Facebook Messenger supported?',
    'What are the support hours and response times for a live business?',
  ],
  ai: {
    easy: ['Gemini Flash or a “mini” tier model', 'Cheapest. Good for FAQs, menus and simple booking questions.'],
    ideal: [['A frontier model with strong tool use (for example Claude Sonnet or the top OpenAI model)', 'Better at multi-step bookings and calling your systems. Costs more per chat.']],
    note: 'OpenAI, Anthropic and Google are reachable from South Africa and bill in US dollars. Keep the model swappable. S10U does not name its AI models on its site, so ask. ⚠',
  },
  mcp: 'MCP (Model Context Protocol) is an open standard that lets an AI model use another tool’s functions, such as “read this calendar” or “create this invoice”. Several popular tools offer MCP servers (for example Zapier, HubSpot, Xero, Stripe, Shopify and Google Workspace). Confirm current status before promising it. ⚠ It is a “later” option here: most demos work with simple connections first.',
  popia: [
    'You are the “responsible party”. S10U, the AI provider and any automation tool are “operators” and need a written operator agreement.',
    'Collect only what you need. Say why when you collect it. Keep it only as long as needed.',
    'Sending data to overseas AI providers is a cross-border transfer. Tell customers, and use providers with a data processing agreement and no training on your data.',
    'Health information is special personal information. Collect booking details only in chat. Send clinical questions to the practice.',
    'Appoint an Information Officer and know how to report a breach to the Information Regulator.',
    'This is a checklist, not legal advice. Get legal sign-off for medical clients.',
  ],
};

export const reviews = {
  fn: 'Reviews and reputation', why: 'Ask happy customers to review you right after the visit.',
  easy: ['Google Business Profile review link', 'Free. Send the link in WhatsApp or show it as a QR code.'],
  ideal: [['Google Business Profile API', 'Read and reply to reviews. Needs Google approval and quota. ⚠'], ['Hellopeter', 'The South African reputation standard. Check its business tools and API. ⚠']],
};
export const crm = (why) => ({
  fn: 'Customer records (CRM)', why,
  easy: ['HubSpot Free CRM', 'Best API and webhooks of the free options. Works with Zapier and Make. Billing is usually in USD or EUR.'],
  ideal: [['Zoho CRM', 'The cost-sensitive South African favourite: local presence, ZAR billing, API and connectors.'], ['HubSpot Starter or Pro', 'More automation when the team grows.'], ['Salesforce', 'For larger firms.']],
});
export const payments = (why) => ({
  fn: 'Payments', why,
  easy: ['Yoco payment links', 'No code. Money settles in South Africa. Send the link in WhatsApp.'],
  ideal: [['Paystack', 'Stripe-owned, launched in South Africa in 2021. API, webhooks, payment links, cards and bank transfer.'], ['Ozow', 'Instant EFT with an API.'], ['PayFast', 'Long-standing South African gateway with callbacks and plugins.'], ['Peach Payments', 'For larger merchants.']],
  note: 'Stripe itself is not generally open to South African businesses. S10U lists in-chat payment requests (cards, EFT, vouchers), so ask which gateways it supports. ⚠',
});
export const accounting = {
  fn: 'Accounting', why: 'Send sales and invoices to your books without retyping.',
  easy: ['Xero', 'Very popular with South African small businesses. ZAR, local bank feeds, open API and webhooks.'],
  ideal: [['Sage Business Cloud Accounting', 'South African-origin, with a REST API. (Sage 50 / Pastel on the desktop has weaker APIs.)'], ['QuickBooks Online or Zoho Books', 'Common alternatives.']],
};
export const handover = {
  fn: 'Team hand-over and alerts', why: 'A person steps in when the bot cannot help.',
  easy: ['S10U inbox with agent hand-over', 'Stated on S10U’s site: assignment, escalation and the full chat history.'],
  ideal: [['Hand-over rules by hours and topic', 'Set who is on duty, and what the bot says outside opening hours.']],
};

export const REQS = {
  'restaurant-booking': {
    intro: 'Florentine’s Bistro takes bookings, pre-orders and payments on WhatsApp. These are the pieces behind each step of the demo.',
    functions: [
      { fn: 'Table availability and bookings', why: 'The bot checks free tables and saves the booking.',
        easy: ['Google Calendar or a Google Sheet', 'Free. The bot writes the booking and staff confirm it.'],
        ideal: [['Dineplan', 'The South African leader and the only local platform with Reserve with Google. Its API is read-only (GET), so the bot can read bookings but not create them. API fee about R190 a month ex VAT per account (check). Plan: staff confirm, or use Dineplan’s own booking widget. ⚠']] },
      { fn: 'Reminders and calendar', why: 'Send the guest an “add to calendar” file and reminders the day before.',
        easy: ['Google Calendar', 'Free, with an API and notifications.'],
        ideal: [['Microsoft 365 / Outlook (Graph API)', 'Common in South African firms.']] },
      { fn: 'Menu and pre-orders', why: 'Guests pick dishes and wine pairings before they arrive.',
        easy: ['Menu in the bot’s knowledge base, orders to a Google Sheet or email', 'Kitchen reads the list. No system links needed.'],
        ideal: [['Lightspeed Restaurant (API)', 'Push pre-orders into the POS.'], ['Yoco POS', 'Popular with small restaurants. Check API openness. ⚠']] },
      payments('Guests pay the bill and tip from WhatsApp.'),
      crm('Remember guests, diets, birthdays and anniversaries.'),
      { fn: 'Loyalty and special days', why: 'Rewards, birthdays and anniversary nudges.',
        easy: ['Points and dates kept in the CRM or a Google Sheet', 'Send nudges with approved broadcast templates (S10U broadcasts include automatic opt-out).'],
        ideal: [['CRM automation (HubSpot or Zoho)', 'Trigger the message 14 days before a date.']] },
      reviews, accounting, handover,
    ],
  },
  'doctors-appointment': {
    intro: 'Greenway Family Practice books, moves and reminds patients on WhatsApp. Health data is sensitive, so the demo only collects booking details.',
    functions: [
      { fn: 'Doctor diary and bookings', why: 'The bot checks free slots and saves the appointment.',
        easy: ['Shared Google Calendar per doctor', 'Free. Staff confirm each booking. Good for a demo or a small practice.'],
        ideal: [['Practice management software: GoodX, Elixir or Healthbridge', 'The real diaries in South African practices. Integration is usually by vendor partnership, not a self-serve API. ⚠']] },
      { fn: 'Medical aid and claims', why: 'Know if the patient uses a medical aid.',
        easy: ['Bot asks, staff check', 'The bot only records “medical aid: yes or no”. Reception verifies.'],
        ideal: [['Healthbridge, MediSwitch or MediKredit', 'Claim switches. Linked through your practice software, not directly from the chat. ⚠']] },
      { fn: 'Reminders and no-show reduction', why: 'Reminders the day before and the morning of, with “confirm / move / cancel” buttons.',
        easy: ['Approved WhatsApp templates sent by S10U', 'S10U’s healthcare case study reports 28% fewer missed consultations with reminders.'],
        ideal: [['Reminders triggered by the practice diary', 'Needs the diary integration above.']] },
      payments('Patients who pay privately can pay a booking fee or the consultation from WhatsApp.'),
      { fn: 'Patient records', why: 'Where the patient file lives.',
        easy: ['Keep clinical records only in your practice software', 'The chat and any sheet hold booking details only: name, time, reference.'],
        ideal: [['Practice software with a patient portal', 'Keeps health data in one regulated place.']],
        note: 'Health information is special personal information under POPIA. Do not collect clinical detail in chat. ⚠' },
      reviews, handover,
    ],
  },
  'customer-support': {
    intro: 'Urban Threads answers questions, tracks orders and starts returns on WhatsApp, and hands over to a person when needed.',
    functions: [
      { fn: 'Order lookup', why: 'The bot finds the customer’s order by number.',
        easy: ['WooCommerce', 'REST API and webhooks. Probably the most common small-shop platform in South Africa (no market-share data).'],
        ideal: [['Shopify', 'Best API and app ecosystem, ZAR supported.'], ['Takealot seller portal', 'If you sell on the marketplace. ⚠']] },
      { fn: 'Courier and tracking', why: 'Show where the parcel is and create return labels.',
        easy: ['The Courier Guy (Ship Logic)', 'API for rate quotes, shipments, labels, tracking and webhooks. Sandbox available. WooCommerce plugin.'],
        ideal: [['Ship Logic V2 API directly', 'Full control of labels and tracking.'], ['Aramex, PUDO, Pargo, Dawn Wing, RAM', 'Check each API. Some are partner-only. ⚠']] },
      { fn: 'Ticketing', why: 'Keep a record of every problem and who solved it.',
        easy: ['Freshdesk (free tier)', 'API, webhooks and Zapier. A Google Sheet works as a ticket log for a demo.'],
        ideal: [['Zendesk', 'The broadest API. Billed in USD.'], ['Zoho Desk', 'ZAR-friendly.'], ['HubSpot Service Hub', 'If you already use HubSpot.']] },
      { fn: 'Knowledge base', why: 'Returns policy, size guides, delivery times, FAQs.',
        easy: ['Upload your FAQs and policies to AI Studio', 'S10U states the chatbot is trained on FAQs, product info and manuals, in 11 languages.'],
        ideal: [['A maintained help centre', 'Keep one source of truth and re-train when it changes.']] },
      handover,
      payments('Refunds and exchange fees go back through your gateway.'),
      crm('Know each customer’s history across chats.'),
      reviews, accounting,
    ],
  },
  'lead-capture': {
    intro: 'SunPeak Energy turns an ad click into a qualified lead and a booked call. These are the pieces behind each step.',
    functions: [
      { fn: 'Where leads come from', why: 'The start of the chat.',
        easy: ['Click-to-WhatsApp ads on Facebook and Instagram', 'Meta gives a free 72-hour messaging window after a click (per Meta’s pricing page).'],
        ideal: [['QR codes, wa.me links and web forms', 'Forms can post to Make or n8n and start a WhatsApp chat. Google Ads message extensions also work. ⚠']] },
      crm('Save each lead with its answers and a score (hot, warm, cold).'),
      { fn: 'Booking the call', why: 'Let the lead pick a time with the advisor.',
        easy: ['Google Calendar', 'Free, with an API.'],
        ideal: [['Calendly', 'API and Zapier. Billed in USD.'], ['Cal.com', 'Open source, API, can be self-hosted.'], ['Microsoft 365 / Outlook', 'If the sales team uses it.']] },
      { fn: 'Scoring and routing', why: 'Decide who gets which lead and how fast.',
        easy: ['AI Studio workflow rules plus a CRM field', 'S10U lists smart routing on customer input.'],
        ideal: [['Make or n8n automation', 'Adds rules, alerts and data from other tools. n8n can be self-hosted, which helps privacy.']] },
      { fn: 'Quotes', why: 'Send a quote PDF on WhatsApp after the call.',
        easy: ['A quote template (Google Docs or a PDF) filled by Zapier or Make', 'Simple and cheap.'],
        ideal: [['Quotes from the CRM, with Xero or Sage for invoicing', 'One system for quote, invoice and payment.']] },
      payments('Take a deposit when the customer accepts.'),
      { fn: 'Follow-up messages', why: 'Remind, nurture and re-engage.',
        easy: ['AI Studio broadcasts with templates', 'Scheduling, link tracking and automatic opt-out are listed by S10U. Opt-in is required.'],
        ideal: [['CRM-triggered sequences', 'For example, message 2 days after the quote if there is no reply.']] },
      handover,
    ],
  },
  'salon-booking': {
    intro: 'Studio Bloom books services, takes deposits and reminds clients on WhatsApp.',
    functions: [
      { fn: 'Stylist calendars and bookings', why: 'The bot checks each stylist’s free times and saves the booking.',
        easy: ['One Google Calendar per stylist', 'Free. Simple and reliable for a demo.'],
        ideal: [['Salon software: Fresha or Booksy', 'Popular salon tools. Fresha is free to start. Check whether the API is open to you, because it may be limited or partner-only. ⚠']] },
      payments('A small deposit secures the booking and cuts no-shows.'),
      { fn: 'Reminders and late notices', why: 'Remind 24 hours and 1 hour before. Clients reply “running late”.',
        easy: ['Approved WhatsApp templates sent by S10U', 'Reminders reach people where they already look.'],
        ideal: [['Reminders triggered by the booking software', 'Needs the booking integration above.']] },
      crm('Remember each client’s services, stylist and last visit.'),
      { fn: 'Rebooking and offers', why: 'Ask for the next visit after six weeks.',
        easy: ['CRM or Google Sheet date plus a broadcast template', 'Opt-in needed.'],
        ideal: [['CRM automation (HubSpot or Zoho)', 'Trigger by last visit date.']] },
      reviews, handover,
    ],
  },
};
