// One entry per use case. The conversation itself lives in uc/<slug>/chat.html (the single source of truth);
// the build script copies it into the dashboard and phone-screens pages.
export const USECASES = [
  {
    slug: 'restaurant-booking',
    lead: "A guest books a table at Florentine’s Bistro using only WhatsApp. The bot collects the date, party size and dietary needs, checks availability, confirms the booking, sends reminders, and later handles the bill and a feedback request.", reference: true,
    name: 'Restaurant Booking', label: 'Restaurant', emoji: '🍷', biz: 'Florentine’s Bistro',
    who: 'guest', journeyTitle: 'Guest Journey – WhatsApp Reservations',
  },
  {
    slug: 'doctors-appointment',
    lead: "Patients book, change or cancel a visit in chat and get reminders before the appointment.",
    name: 'Doctor\'s Appointment', label: 'Doctor', emoji: '🩺', biz: 'Greenway Family Practice',
    who: 'patient', journeyTitle: 'Patient Journey – WhatsApp Appointments',
    active: 'Sarah van der Merwe',
    contacts: [
      ['Thabo Mokoena', '12 min ago', 'Appointment confirmed. See you Friday!'],
      ['Emma Clarke', '1 hour ago', 'Could we move to the afternoon?'],
      ['Pieter Botha', 'Yesterday', 'Thank you, see you next month'],
      ['Aisha Patel', 'Sep 29, 2026', 'Thanks for the reminder 👍'],
    ],
    summary: [
      'Patient asked to see a doctor.',
      'General consultation with the first available doctor.',
      '18/11/2026 at 10:30 with Dr van Wyk.',
      'Visit is for the patient. Pays privately.',
      'Slot checked and held for 10 minutes.',
      'Appointment confirmed. Ref GW-2026-0318.',
      'Reminders sent: the day before and the morning of.',
      'Moved to 20/11/2026 at 11:00.',
      'Rated the visit 5 – Excellent. Follow-up offered.',
    ],
  },
  {
    slug: 'customer-support',
    lead: "Customers get instant answers on WhatsApp. The bot handles common questions, looks up orders, starts returns, and hands over to a person when needed.",
    name: 'Customer Support', label: 'Support', emoji: '🎧', biz: 'Urban Threads',
    who: 'customer', journeyTitle: 'Customer Journey – WhatsApp Support',
    active: 'Lindiwe Zulu',
    contacts: [
      ['Sipho Ndlovu', '12 min ago', 'Where is my parcel?'],
      ['Emma Clarke', '1 hour ago', 'Thanks, sorted!'],
      ['Pieter Botha', 'Yesterday', 'Can I change my delivery address?'],
      ['Aisha Patel', 'Sep 29, 2026', 'Return label received 👍'],
    ],
    summary: [
      'Customer needs help with an order.',
      'Asked about returns. Policy answered; still needs help.',
      'Order ORD-48213 found: shipped, arrives 14/11/2026.',
      'Return started: running shoes, wrong size.',
      'Handed over to Priya for a size exchange.',
      'Exchange booked. Ref UT-2026-0589. Label sent.',
      'Rated 5 – Excellent. Chat closed.',
    ],
  },
  {
    slug: 'lead-capture',
    lead: "A customer taps an ad and lands in a WhatsApp chat. The bot asks a few questions, scores the lead, books a call with an advisor and follows up.",
    name: 'Lead Capture', label: 'Lead', emoji: '📣', biz: 'SunPeak Energy',
    who: 'lead', journeyTitle: 'Lead Journey – WhatsApp Lead Capture',
    active: 'Thandi Mokoena',
    contacts: [
      ['Pieter Botha', '12 min ago', 'Thanks, the quote looks good'],
      ['Lindiwe Zulu', '1 hour ago', 'I own the property'],
      ['Michael Brown', 'Yesterday', 'Call booked for Thursday'],
      ['Aisha Patel', 'Sep 29, 2026', 'Not now, thank you'],
    ],
    summary: [
      'Came from a Facebook ad asking for a solar quote.',
      'Owns the property. Bill R1 000 – R2 500 a month.',
      'Suburb: Durbanville. Tiled roof.',
      'Roof photo received.',
      'Estimate given: about 5 kW, around 50% saving.',
      'Call booked tomorrow at 11:30. Ref SP-2026-0231.',
      'Lead saved to the CRM. Score: Hot.',
      'Reminder sent. Quote PDF sent after the call.',
    ],
  },
  {
    slug: 'salon-booking',
    lead: "Clients book a service with their favourite stylist on WhatsApp, pay a small deposit, get reminders and rebook after the visit.",
    name: 'Salon Booking', label: 'Salon', emoji: '💇', biz: 'Studio Bloom',
    who: 'client', journeyTitle: 'Client Journey – WhatsApp Bookings',
    active: 'Naledi Khumalo',
    contacts: [
      ['Zanele Dube', '12 min ago', 'Booking confirmed. See you Saturday!'],
      ['Megan Smith', '1 hour ago', 'Can I move to 14:00?'],
      ['Ayesha Patel', 'Yesterday', 'Thank you, love my hair 💚'],
      ['Johan Pretorius', 'Sep 29, 2026', 'Deposit received'],
    ],
    summary: [
      'Client wants to book an appointment.',
      'Service: half head highlights (R850).',
      'Stylist: Lerato.',
      'Saturday 21/11/2026 at 11:30.',
      'Blow-dry added. R100 deposit paid.',
      'Booking confirmed. Ref SB-2026-0077. Total R970.00.',
      'Reminders sent. Client running 10 minutes late.',
      'Rated 5 – Loved it. Rebooking in 6 weeks.',
    ],
  },
];
